export type GlossaryCategoryId = 'credit' | 'rates' | 'products' | 'process' | 'legal' | 'islamic' | 'property' | 'general';

export interface GlossaryTerm {
  term: string;
  slug: string;
  definition: string;
  category: GlossaryCategoryId;
  related: string[];
  example: string;
}

export const glossaryUi = {
  en: {
    breadcrumbHome: 'Home',
    breadcrumbGlossary: 'Glossary',
    title: 'Financial Glossary',
    subtitle: 'Understanding loan and credit terminology',
    lede: 'A comprehensive guide to financial terms commonly used in Malaysia. Search or browse by category to understand the language of loans and credit.',
    searchPlaceholder: 'Search terms...',
    allCategories: 'All',
    categories: {
      credit: 'Credit & Scoring',
      rates: 'Rates & Fees',
      products: 'Loan Products',
      process: 'Process & Terms',
      legal: 'Legal & Compliance',
      islamic: 'Islamic Financing',
      property: 'Property',
      general: 'Documents & Income',
    },
    showMore: 'Show More',
    showLess: 'Show Less',
    relatedTerms: 'Related Terms',
    example: 'Example',
    quickNav: {
      title: 'Quick Navigation',
      subtitle: 'Jump to a section',
    },
    noResults: 'No terms found. Try a different search.',
  },
  ms: {
    breadcrumbHome: 'Utama',
    breadcrumbGlossary: 'Glosari',
    title: 'Glosari Kewangan',
    subtitle: 'Memahami terminologi pinjaman dan kredit',
    lede: 'Panduan komprehensif istilah kewangan yang biasa digunakan di Malaysia. Cari atau layari mengikut kategori untuk memahami bahasa pinjaman dan kredit.',
    searchPlaceholder: 'Cari istilah...',
    allCategories: 'Semua',
    categories: {
      credit: 'Kredit & Skor',
      rates: 'Kadar & Yuran',
      products: 'Produk Pinjaman',
      process: 'Proses & Terma',
      legal: 'Undang-undang & Pematuhan',
      islamic: 'Pembiayaan Islam',
      property: 'Hartanah',
      general: 'Dokumen & Pendapatan',
    },
    showMore: 'Tunjuk Lagi',
    showLess: 'Tunjuk Kurang',
    relatedTerms: 'Istilah Berkaitan',
    example: 'Contoh',
    quickNav: {
      title: 'Navigasi Pantas',
      subtitle: 'Lompat ke bahagian',
    },
    noResults: 'Tiada istilah dijumpai. Cuba carian lain.',
  },
} as const;

export const glossaryTerms: { en: GlossaryTerm[]; ms: GlossaryTerm[] } = {
  en: [
    // ── Credit ──────────────────────────────────────────────────────────
    {
      term: 'CCRIS',
      slug: 'ccris',
      definition: 'Central Credit Reference Information System — a system maintained by Bank Negara Malaysia showing the credit facilities you hold and the last 12 months of repayment conduct as reported by banks.',
      category: 'credit',
      related: ['ctos', 'credit-score', 'credit-report'],
      example: 'When you apply for a loan, banks check your CCRIS report to see your outstanding facilities and recent repayment conduct.',
    },
    {
      term: 'CTOS',
      slug: 'ctos',
      definition: 'A private credit reporting agency in Malaysia. Unlike CCRIS, a CTOS report can also include non-banking information such as legal case records and trade references.',
      category: 'credit',
      related: ['ccris', 'credit-score', 'trade-reference'],
      example: 'We obtain a CTOS report as part of our review, which is why the RM30 fee mentioned in our FAQ exists.',
    },
    {
      term: 'Credit Score',
      slug: 'credit-score',
      definition: 'A numerical summary of creditworthiness, expressed as a score rather than a pass/fail result. The exact scale can change over time, so confirm the current scale directly with CTOS.',
      category: 'credit',
      related: ['ccris', 'ctos', 'credit-report'],
      example: 'A higher CTOS Score generally makes it easier to be matched with more lenders, though it never guarantees approval.',
    },
    {
      term: 'Credit Report',
      slug: 'credit-report',
      definition: 'A detailed document summarising your credit facilities, repayment history, and any related legal records, compiled from sources such as CCRIS and CTOS.',
      category: 'credit',
      related: ['ccris', 'ctos', 'credit-score'],
      example: 'Reviewing your own credit report before applying can help you spot and correct errors early.',
    },
    {
      term: 'DSR',
      slug: 'dsr',
      definition: 'Debt Service Ratio — the percentage of your gross monthly income committed to debt repayments. Most banks use a guideline of around 60%, though this varies by bank and profile.',
      category: 'credit',
      related: ['ndi', 'akpk', 'personal-loan'],
      example: 'If your monthly income is RM5,000 and your total debt repayments are RM2,000, your DSR is roughly 40%.',
    },
    {
      term: 'NDI (Net Disposable Income)',
      slug: 'ndi',
      definition: 'The income left over after statutory deductions and committed debt repayments. Some banks look at NDI alongside DSR to judge whether a borrower can comfortably service a new loan.',
      category: 'credit',
      related: ['dsr', 'akpk'],
      example: 'A borrower with a high salary but very little NDI after existing commitments may still find approval harder.',
    },
    {
      term: 'Default',
      slug: 'default',
      definition: 'Failure to repay a loan according to its agreed terms. A default is reflected in your CCRIS conduct record and can make future approvals harder to obtain.',
      category: 'credit',
      related: ['npl', 'credit-score'],
      example: 'Missing several consecutive instalments without contacting your bank can eventually be recorded as a default.',
    },
    {
      term: 'NPL',
      slug: 'npl',
      definition: 'Non-Performing Loan — industry shorthand for a loan where repayments have been missed for an extended period, generally considered a serious mark on a credit record.',
      category: 'credit',
      related: ['default', 'credit-score'],
      example: 'Banks monitor their NPL ratio closely, which is one reason underwriting can tighten during difficult economic periods.',
    },
    {
      term: 'AKPK',
      slug: 'akpk',
      definition: 'Agensi Kaunseling dan Pengurusan Kredit — a government-backed agency that provides free debt counselling and financial education to Malaysian borrowers.',
      category: 'credit',
      related: ['akpk-dmp', 'dsr'],
      example: 'If you are juggling several debts, AKPK can review your finances and suggest a realistic way forward at no cost.',
    },
    {
      term: 'AKPK DMP',
      slug: 'akpk-dmp',
      definition: "AKPK's Debt Management Programme — a structured repayment plan that AKPK arranges directly with your participating banks when you are struggling to keep up with multiple debts.",
      category: 'credit',
      related: ['akpk', 'restructuring'],
      example: 'Enrolling in the DMP can consolidate several bank repayments into one manageable monthly plan negotiated on your behalf.',
    },
    {
      term: 'Bankruptcy Threshold',
      slug: 'bankruptcy-threshold',
      definition: 'The minimum debt amount above which a creditor can file for a debtor to be declared bankrupt in Malaysia. RM100,000 is the current threshold — verify the latest figure, as thresholds can change over time.',
      category: 'credit',
      related: ['bankruptcy', 'default'],
      example: 'Because the threshold can be revised, always check the current figure rather than relying on an older source.',
    },
    {
      term: 'Credit Utilization',
      slug: 'credit-utilization',
      definition: 'The proportion of your available revolving credit (mainly credit cards) that is currently in use. High utilisation relative to your limits can be viewed less favourably during assessment.',
      category: 'credit',
      related: ['credit-score', 'dsr'],
      example: 'Paying down credit card balances before applying can improve both your utilisation and your overall profile.',
    },
    {
      term: 'Trade Reference',
      slug: 'trade-reference',
      definition: 'A non-banking payment record, such as a supplier or trade account, that CTOS may include in its reports — one way CTOS data differs from the purely banking data in CCRIS.',
      category: 'credit',
      related: ['ctos', 'credit-report'],
      example: 'A business owner with a poor trade reference on file may see it reflected in their CTOS report.',
    },

    // ── Rates ───────────────────────────────────────────────────────────
    {
      term: 'Flat Rate',
      slug: 'flat-rate',
      definition: 'An interest calculation method where interest is charged on the original principal for the entire tenure, regardless of how much has already been repaid.',
      category: 'rates',
      related: ['effective-rate', 'eir', 'personal-loan'],
      example: 'Personal loans we help arrange are commonly quoted from 4.88% flat per annum, for tenures of up to 7 years.',
    },
    {
      term: 'Effective Rate',
      slug: 'effective-rate',
      definition: 'An interest calculation method based on the reducing principal balance, so the interest portion shrinks as you repay — often a more accurate reflection of true cost than a flat rate.',
      category: 'rates',
      related: ['flat-rate', 'eir'],
      example: 'A flat rate and an effective rate on the same loan can look similar on paper but cost noticeably different amounts overall.',
    },
    {
      term: 'EIR',
      slug: 'eir',
      definition: 'Effective Interest Rate — a standardised way of expressing the true cost of borrowing, including compounding, so loans with different rate structures can be compared more fairly.',
      category: 'rates',
      related: ['flat-rate', 'effective-rate', 'apr'],
      example: 'Two loans with the same flat rate can still have different EIRs depending on fees and repayment structure.',
    },
    {
      term: 'APR',
      slug: 'apr',
      definition: 'Annual Percentage Rate — a rate measure that can incorporate certain fees on top of interest. Not every lender in Malaysia quotes APR the same way, so always confirm exactly what is included.',
      category: 'rates',
      related: ['eir', 'flat-rate'],
      example: 'Ask your lender to show what fees, if any, are folded into the APR figure they quote you.',
    },
    {
      term: 'Base Rate (BR)',
      slug: 'base-rate',
      definition: "A reference lending rate each bank sets based on its own funding cost and other factors; a borrower's actual rate is typically the Base Rate plus a margin.",
      category: 'rates',
      related: ['base-lending-rate', 'opr'],
      example: 'When a bank\'s Base Rate rises, variable-rate loans priced off it typically become more expensive.',
    },
    {
      term: 'Base Lending Rate (BLR)',
      slug: 'base-lending-rate',
      definition: 'An older reference-rate framework that predates the Base Rate system. Some legacy loan agreements still price off BLR rather than the newer benchmarks.',
      category: 'rates',
      related: ['base-rate', 'opr'],
      example: 'If your loan agreement mentions BLR rather than BR or SBR, it may be an older facility with a different pricing structure.',
    },
    {
      term: 'Standard Base Rate (SBR)',
      slug: 'standard-base-rate',
      definition: "A benchmark reference rate framework introduced by Bank Negara Malaysia, informed by the OPR, used by banks to price certain retail financing products.",
      category: 'rates',
      related: ['opr', 'base-rate'],
      example: 'A change in SBR-linked loans generally follows shortly after a change in the OPR.',
    },
    {
      term: 'OPR',
      slug: 'opr',
      definition: 'Overnight Policy Rate — the benchmark interest rate set by Bank Negara Malaysia that influences lending rates across the economy, including many variable-rate loans.',
      category: 'rates',
      related: ['base-rate', 'standard-base-rate'],
      example: 'When Bank Negara Malaysia raises the OPR, borrowers on variable-rate loans often see their instalments increase.',
    },
    {
      term: 'Processing Fee',
      slug: 'processing-fee',
      definition: 'A one-time administrative fee that some lenders charge to process a loan application. Whether it applies, and how much, varies by lender and is disclosed in the written offer.',
      category: 'rates',
      related: ['stamp-duty', 'loan-agreement'],
      example: 'Always check the written offer for any processing fee rather than assuming a fixed percentage applies.',
    },
    {
      term: 'Stamp Duty',
      slug: 'stamp-duty',
      definition: "A government duty payable on certain loan documents under the Stamp Act. Whether it applies to your loan, and the amount, is disclosed in the written offer rather than a single fixed rate you should assume.",
      category: 'rates',
      related: ['stamp-act', 'processing-fee', 'loan-agreement'],
      example: 'Two borrowers with similar loans may see different stamp duty treatment depending on the product and documentation used.',
    },
    {
      term: 'Early Settlement Rebate (Rule of 78)',
      slug: 'early-settlement-rebate',
      definition: 'Some lenders calculate the interest rebate on early settlement using a sum-of-digits method known as the Rule of 78, which weights more interest to the early part of a loan. The exact rebate you receive depends on your specific agreement.',
      category: 'rates',
      related: ['settlement', 'lock-in-period'],
      example: 'Settling a loan in its first year under a Rule of 78 structure typically yields a smaller rebate than settling closer to the end of the tenure.',
    },
    {
      term: 'Late Payment Charge',
      slug: 'late-payment-charge',
      definition: 'A charge applied when an instalment is not paid by its due date, as set out in the loan agreement. A late payment can also be reflected in your CCRIS conduct record.',
      category: 'rates',
      related: ['ccris', 'loan-agreement'],
      example: 'Setting up an auto-debit instruction is one way borrowers try to avoid late payment charges.',
    },
    {
      term: 'Lock-in Period',
      slug: 'lock-in-period',
      definition: 'A period during which settling or refinancing a loan early triggers a penalty under the agreement. Terms and duration vary by lender and product.',
      category: 'rates',
      related: ['early-settlement-rebate', 'refinancing'],
      example: 'Check whether your home loan is still within its lock-in period before applying to refinance elsewhere.',
    },
    {
      term: 'Grace Period',
      slug: 'grace-period',
      definition: 'A short window, if offered by the lender, after a due date or after disbursement during which no late charge applies. It is not guaranteed on every loan product.',
      category: 'rates',
      related: ['late-payment-charge', 'moratorium'],
      example: 'A short grace period can give a borrower a few extra days to make a payment without incurring a late charge.',
    },

    // ── Products ────────────────────────────────────────────────────────
    {
      term: 'Personal Loan',
      slug: 'personal-loan',
      definition: 'An unsecured loan for personal use such as emergencies, medical bills, or consolidating other debts. Personal loans we help arrange go up to RM100,000, over 1 to 7 years, from 4.88% flat per annum.',
      category: 'products',
      related: ['flat-rate', 'dsr', 'unsecured-loan'],
      example: 'A personal loan does not require you to pledge any asset, but approval still depends on your income and credit profile.',
    },
    {
      term: 'Business Loan',
      slug: 'business-loan',
      definition: 'Financing for small and medium enterprises or companies, generally assessed on business cash flow and, for some products, collateral, rather than personal payslips alone.',
      category: 'products',
      related: ['collateral', 'dsr'],
      example: 'A retailer might use a business loan to fund inventory ahead of a busy season.',
    },
    {
      term: 'Car Loan',
      slug: 'car-loan',
      definition: 'Financing for purchasing a vehicle, commonly structured as hire purchase, where the financier retains an interest in the vehicle until the final instalment is paid.',
      category: 'products',
      related: ['hire-purchase', 'collateral'],
      example: 'Most car loans in Malaysia are arranged through hire purchase agreements rather than unsecured personal loans.',
    },
    {
      term: 'Hire Purchase',
      slug: 'hire-purchase',
      definition: 'A financing arrangement, commonly used for vehicles, where you pay in instalments while using the asset. Ownership only transfers to you once all payments are completed.',
      category: 'products',
      related: ['car-loan', 'collateral'],
      example: 'Under hire purchase, the financier technically retains an interest in the car until the final instalment clears.',
    },
    {
      term: 'Home Loan',
      slug: 'home-loan',
      definition: 'A secured loan for purchasing property, with the property itself serving as collateral. These loans typically have longer tenures than personal financing.',
      category: 'products',
      related: ['mrta', 'ltv', 'collateral'],
      example: 'A home loan\'s approved amount is usually capped by the property\'s LTV limit as well as your DSR.',
    },
    {
      term: 'Secured Loan',
      slug: 'secured-loan',
      definition: 'A loan backed by collateral. If the borrower fails to repay, the lender may be able to seize the pledged asset, following the process set out in the agreement.',
      category: 'products',
      related: ['collateral', 'unsecured-loan', 'home-loan'],
      example: 'Home loans and many car loans are secured loans, since the property or vehicle backs the financing.',
    },
    {
      term: 'Unsecured Loan',
      slug: 'unsecured-loan',
      definition: 'A loan not backed by any collateral, relying instead on the borrower\'s income and credit profile. Personal loans are typically unsecured.',
      category: 'products',
      related: ['personal-loan', 'secured-loan'],
      example: 'Because no asset backs an unsecured loan, lenders generally weigh income and CCRIS/CTOS records more heavily.',
    },
    {
      term: 'Refinancing',
      slug: 'refinancing',
      definition: 'Replacing an existing loan with a new one, usually to obtain better terms such as a lower rate or a different tenure.',
      category: 'products',
      related: ['home-loan', 'lock-in-period'],
      example: 'A borrower might refinance a home loan to take advantage of a lower prevailing rate, subject to any lock-in period.',
    },
    {
      term: 'Debt Consolidation',
      slug: 'debt-consolidation',
      definition: 'Combining several existing debts into a single new loan with one monthly instalment, which can simplify repayment and, depending on the new terms, change the total monthly outlay.',
      category: 'products',
      related: ['personal-loan', 'dsr'],
      example: 'Consolidating three separate debts into one loan can make it easier to track a single due date each month.',
    },
    {
      term: 'Top-up Loan',
      slug: 'top-up-loan',
      definition: 'Additional financing added on top of an existing loan, commonly a home loan, usually secured against the same collateral and subject to fresh bank approval.',
      category: 'products',
      related: ['home-loan', 'collateral'],
      example: 'A homeowner might apply for a top-up loan against an existing home loan to fund renovations.',
    },
    {
      term: 'Balance Transfer',
      slug: 'balance-transfer',
      definition: 'Moving an outstanding balance, such as credit card debt, to a new facility, sometimes at a promotional rate for a limited period. Terms vary by issuer.',
      category: 'products',
      related: ['debt-consolidation', 'effective-rate'],
      example: 'A balance transfer can temporarily reduce interest costs, but check what rate applies once the promotional period ends.',
    },
    {
      term: 'Guarantor',
      slug: 'guarantor',
      definition: 'A person who agrees to repay a loan if the primary borrower cannot. A guarantor is liable only upon the borrower\'s default, unlike a joint borrower.',
      category: 'products',
      related: ['joint-borrower', 'credit-score'],
      example: 'Having a guarantor with a strong credit profile can sometimes help an otherwise borderline application.',
    },
    {
      term: 'Joint Borrower',
      slug: 'joint-borrower',
      definition: 'An applicant who applies together with the primary borrower and shares full, ongoing repayment responsibility, rather than only stepping in upon default like a guarantor.',
      category: 'products',
      related: ['guarantor', 'dsr'],
      example: 'Applying with a joint borrower can combine two incomes, which may help meet a bank\'s DSR requirement.',
    },
    {
      term: 'Collateral',
      slug: 'collateral',
      definition: 'An asset pledged as security for a loan. If the borrower defaults, the lender may pursue the collateral through the process set out in the agreement.',
      category: 'products',
      related: ['secured-loan', 'foreclosure'],
      example: 'Property and vehicles are the most common forms of collateral in Malaysian consumer lending.',
    },
    {
      term: 'Emergency Loan',
      slug: 'emergency-loan',
      definition: 'Fast-turnaround personal financing intended for urgent expenses, generally following the same eligibility and documentation standards as other personal loans.',
      category: 'products',
      related: ['personal-loan', 'dsr'],
      example: 'An emergency loan can help cover an unexpected medical bill while you sort out longer-term finances.',
    },

    // ── Process ─────────────────────────────────────────────────────────
    {
      term: 'Disbursement',
      slug: 'disbursement',
      definition: 'The release of approved loan funds to the borrower, typically paid directly into a bank account once the offer is accepted. Timing varies by lender and product.',
      category: 'process',
      related: ['letter-of-offer', 'settlement'],
      example: 'For some property loans, disbursement happens in stages tied to construction progress rather than all at once.',
    },
    {
      term: 'Cooling-off Period',
      slug: 'cooling-off',
      definition: 'A short window after signing during which some agreements allow a borrower to cancel without penalty, if the specific contract provides for it — check your own offer, as it is not automatic on every loan.',
      category: 'process',
      related: ['loan-agreement', 'letter-of-offer'],
      example: 'Some product agreements include a brief cooling-off period; ask your lender to confirm before you sign.',
    },
    {
      term: 'e-KYC',
      slug: 'e-kyc',
      definition: 'Electronic Know-Your-Customer — a digital identity-verification process, often combining a selfie with an IC scan, that lets applicants onboard without visiting a branch in person.',
      category: 'process',
      related: ['ic', 'mykad', 'e-signature'],
      example: 'e-KYC lets you verify your identity from home instead of visiting a branch counter.',
    },
    {
      term: 'Amortization',
      slug: 'amortization',
      definition: 'The process of spreading loan repayments over time. An amortisation schedule shows how each instalment splits between principal and interest across the tenure.',
      category: 'process',
      related: ['principal', 'installment', 'tenure'],
      example: 'Early in an amortising loan, a larger share of each instalment typically goes toward interest rather than principal.',
    },
    {
      term: 'Tenure',
      slug: 'tenure',
      definition: 'The length of time you have to repay a loan. A longer tenure generally lowers the monthly instalment but increases total interest paid over the life of the loan.',
      category: 'process',
      related: ['installment', 'amortization'],
      example: 'A personal loan\'s tenure typically runs from 1 to 7 years, while a home loan can run much longer.',
    },
    {
      term: 'Moratorium',
      slug: 'moratorium',
      definition: 'A temporary suspension or deferment of loan instalments that a lender may grant during periods of hardship. Availability, duration, and terms are decided by each bank.',
      category: 'process',
      related: ['restructuring', 'rescheduling'],
      example: 'A short moratorium can give a borrower breathing room after a sudden loss of income, if the bank agrees to grant one.',
    },
    {
      term: 'Restructuring',
      slug: 'restructuring',
      definition: "A lender-approved change to a loan's terms, such as its tenure or rate, agreed on a case-by-case basis for a borrower facing genuine financial difficulty.",
      category: 'process',
      related: ['moratorium', 'rescheduling', 'akpk-dmp'],
      example: 'Restructuring might extend a loan\'s tenure to lower the monthly instalment to a more manageable level.',
    },
    {
      term: 'Rescheduling',
      slug: 'rescheduling',
      definition: 'Adjusting the repayment schedule of an existing loan, such as spreading remaining payments over a longer period, usually to reduce the instalment amount.',
      category: 'process',
      related: ['restructuring', 'moratorium'],
      example: 'Rescheduling a loan can lower the monthly commitment, though it may increase the total interest paid overall.',
    },
    {
      term: 'Letter of Offer',
      slug: 'letter-of-offer',
      definition: 'A formal document from a bank confirming the approved loan amount, rate, tenure, and all associated terms and fees. Signing it commits you to the loan.',
      category: 'process',
      related: ['loan-agreement', 'disbursement'],
      example: 'Read every line of the letter of offer, including the fee schedule, before signing.',
    },
    {
      term: 'Principal',
      slug: 'principal',
      definition: 'The original amount borrowed, excluding interest and fees. Each instalment repays part principal and part interest.',
      category: 'process',
      related: ['installment', 'amortization'],
      example: 'Making an extra payment toward principal can shorten a loan\'s remaining tenure.',
    },
    {
      term: 'Installment',
      slug: 'installment',
      definition: 'Each scheduled periodic payment, usually monthly, that covers part principal and part interest under an amortising loan.',
      category: 'process',
      related: ['principal', 'tenure'],
      example: 'A longer tenure spreads the same principal across more, smaller instalments.',
    },
    {
      term: 'Loan Agreement',
      slug: 'loan-agreement',
      definition: 'The binding contract setting out the principal, rate, tenure, fees, and conditions governing a loan. Read it fully before signing.',
      category: 'process',
      related: ['letter-of-offer', 'stamp-duty'],
      example: 'Any fee mentioned only verbally should still appear in writing in the loan agreement before you sign.',
    },
    {
      term: 'Settlement',
      slug: 'settlement',
      definition: 'Full repayment of a loan\'s outstanding balance, either at the end of its tenure or ahead of schedule.',
      category: 'process',
      related: ['early-settlement-rebate', 'disbursement'],
      example: 'Requesting a settlement figure from your bank tells you exactly what is owed to close the loan today.',
    },

    // ── Legal ───────────────────────────────────────────────────────────
    {
      term: 'PDPA',
      slug: 'pdpa',
      definition: 'The Personal Data Protection Act 2010 — Malaysia\'s law governing how organisations may collect, use, store, and disclose personal data, including borrowers\' information.',
      category: 'legal',
      related: ['e-kyc', 'bank-statement'],
      example: 'A lender should explain, in line with the PDPA, how your submitted bank statements will be stored and used.',
    },
    {
      term: 'Moneylenders Act 1951',
      slug: 'moneylenders-act-1951',
      definition: 'The law under which licensed moneylenders in Malaysia are regulated, with licensing and enforcement overseen by KPKT.',
      category: 'legal',
      related: ['kpkt-licence', 'ah-long'],
      example: 'A moneylender operating without a licence under the Moneylenders Act 1951 is acting illegally.',
    },
    {
      term: 'KPKT Licence',
      slug: 'kpkt-licence',
      definition: 'A licence issued under the Moneylenders Act 1951 by the Ministry of Local Government Development (KPKT), required to lawfully operate as a moneylender in Malaysia.',
      category: 'legal',
      related: ['moneylenders-act-1951', 'loan-shark-red-flags'],
      example: 'You can ask any licensed moneylender to share their KPKT licensing details through an official channel.',
    },
    {
      term: 'Ah Long',
      slug: 'ah-long',
      definition: 'A colloquial term for an unlicensed, illegal lender ("loan shark"). Dealing with an Ah Long carries serious financial and personal risk, including harassment.',
      category: 'legal',
      related: ['loan-shark-red-flags', 'moneylenders-act-1951'],
      example: 'Victims of Ah Long harassment are encouraged to lodge a report with the police rather than continue paying.',
    },
    {
      term: 'Loan Shark Red Flags',
      slug: 'loan-shark-red-flags',
      definition: 'Warning signs of illegal lending, such as no written agreement, upfront "unlock" fees, threats, or contact only through unofficial channels. Legitimate licensed lenders disclose terms in writing.',
      category: 'legal',
      related: ['ah-long', 'kpkt-licence'],
      example: 'Being asked to pay an upfront fee before any review has taken place is a classic loan shark red flag.',
    },
    {
      term: 'Bankruptcy',
      slug: 'bankruptcy',
      definition: 'A legal status in which a person is declared unable to pay their debts. In Malaysia, bankruptcy restricts activities such as obtaining new credit or holding a company directorship.',
      category: 'legal',
      related: ['bankruptcy-threshold', 'default'],
      example: 'Being declared bankrupt can affect your ability to travel overseas or hold certain professional positions.',
    },
    {
      term: 'Foreclosure',
      slug: 'foreclosure',
      definition: 'The legal process by which a lender takes possession of collateral, such as a property, when a borrower fails to repay a secured loan — generally a last resort.',
      category: 'legal',
      related: ['collateral', 'secured-loan'],
      example: 'Banks typically pursue restructuring options with a struggling borrower well before initiating foreclosure.',
    },
    {
      term: 'Stamp Act',
      slug: 'stamp-act',
      definition: 'The legislation governing stamp duty on documents, including loan agreements. The amount payable on your loan, if any, is disclosed in the written offer rather than a single public rate you should assume.',
      category: 'legal',
      related: ['stamp-duty', 'loan-agreement'],
      example: 'Ask your lender to point out the exact stamp duty line item in your offer rather than estimating it yourself.',
    },

    // ── Islamic Financing ───────────────────────────────────────────────
    {
      term: 'Murabahah',
      slug: 'murabahah',
      definition: 'A cost-plus-profit sale structure where the financier buys an asset and sells it to the customer at a disclosed mark-up, repaid in instalments.',
      category: 'islamic',
      related: ['shariah-compliant', 'profit-rate'],
      example: 'Some Islamic personal financing products in Malaysia use a Murabahah structure instead of a conventional interest-based loan.',
    },
    {
      term: 'Tawarruq',
      slug: 'tawarruq',
      definition: 'A commodity-based financing structure involving the sale and resale of an underlying asset to generate cash for the customer, arranged to be Shariah-compliant.',
      category: 'islamic',
      related: ['shariah-compliant', 'murabahah'],
      example: 'Tawarruq is commonly used to structure Islamic personal financing and credit cards in Malaysia.',
    },
    {
      term: "Bai' Al-Inah",
      slug: 'bai-al-inah',
      definition: 'A sale-and-buy-back structure used in some Islamic financing products. Its permissibility is debated among scholars in different jurisdictions, so exact terms vary by institution.',
      category: 'islamic',
      related: ['shariah-compliant', 'tawarruq'],
      example: "Ask your bank which structure — Bai' Al-Inah, Tawarruq, or another — underlies a specific Islamic product before comparing it.",
    },
    {
      term: 'Ijarah',
      slug: 'ijarah',
      definition: 'A lease-based structure where the financier owns an asset and leases it to the customer for a rental (profit) payment, common in Islamic hire-purchase and property financing.',
      category: 'islamic',
      related: ['shariah-compliant', 'profit-rate'],
      example: 'An Ijarah structure is often used for Islamic vehicle and home financing in Malaysia.',
    },
    {
      term: 'Takaful',
      slug: 'takaful',
      definition: 'A Shariah-compliant alternative to conventional insurance, based on mutual contribution and shared risk among participants.',
      category: 'islamic',
      related: ['shariah-compliant', 'mrta'],
      example: 'A Takaful plan can serve a similar protective role to MRTA for borrowers who prefer a Shariah-compliant option.',
    },
    {
      term: 'Shariah-compliant',
      slug: 'shariah-compliant',
      definition: 'Describes a financial product structured to comply with Islamic law, avoiding interest (riba) in favour of profit-sharing or fee-based structures overseen by a Shariah committee.',
      category: 'islamic',
      related: ['islamic-financing', 'profit-rate'],
      example: 'A Shariah-compliant loan replaces an interest rate with a disclosed profit rate under an approved contract structure.',
    },
    {
      term: 'Profit Rate',
      slug: 'profit-rate',
      definition: 'The Islamic-finance equivalent of an interest rate — the return a financier earns under a Shariah-compliant structure such as Murabahah or Ijarah.',
      category: 'islamic',
      related: ['shariah-compliant', 'murabahah'],
      example: 'Comparing profit rates across Islamic products works much like comparing interest rates on conventional loans.',
    },
    {
      term: 'Islamic Financing',
      slug: 'islamic-financing',
      definition: 'An umbrella term for Shariah-compliant financing products. Availability depends on the specific bank and product at the time you apply — ask us and we will confirm what is currently offered.',
      category: 'islamic',
      related: ['shariah-compliant', 'murabahah', 'ijarah'],
      example: 'Islamic financing is available for some, but not necessarily all, loan products we help arrange.',
    },
    {
      term: 'Wakalah',
      slug: 'wakalah',
      definition: 'An agency contract where one party (the agent) acts on behalf of another (the principal), used within some Islamic financing and Takaful structures.',
      category: 'islamic',
      related: ['shariah-compliant', 'takaful'],
      example: 'A Wakalah arrangement may appoint the bank as an agent to carry out a transaction on the customer\'s behalf.',
    },
    {
      term: 'Musyarakah Mutanaqisah',
      slug: 'musyarakah-mutanaqisah',
      definition: 'A diminishing-partnership structure, common in Islamic home financing, where the bank and customer jointly own an asset and the customer gradually buys out the bank\'s share over time.',
      category: 'islamic',
      related: ['ijarah', 'home-loan', 'shariah-compliant'],
      example: 'Under Musyarakah Mutanaqisah, each instalment increases the customer\'s ownership share in the property.',
    },

    // ── Property ────────────────────────────────────────────────────────
    {
      term: 'MRTA',
      slug: 'mrta',
      definition: 'Mortgage Reducing Term Assurance — a decreasing term insurance that covers the outstanding balance of a home loan if the borrower passes away or becomes permanently disabled.',
      category: 'property',
      related: ['mlta', 'home-loan'],
      example: 'MRTA coverage typically decreases roughly in line with your home loan\'s outstanding balance over time.',
    },
    {
      term: 'MLTA',
      slug: 'mlta',
      definition: 'Mortgage Level Term Assurance — unlike MRTA, this maintains a fixed coverage amount throughout the loan tenure, generally at a higher cost but with more consistent protection.',
      category: 'property',
      related: ['mrta', 'home-loan'],
      example: 'A borrower who wants coverage to remain constant even as the loan balance falls might choose MLTA over MRTA.',
    },
    {
      term: 'LTV / Margin of Finance',
      slug: 'ltv',
      definition: "Loan-to-Value — the loan amount expressed as a percentage of a property's value or purchase price, whichever is lower. The maximum allowed varies by bank and property type.",
      category: 'property',
      related: ['home-loan', 'valuation'],
      example: 'An 80% LTV on a RM500,000 property means the bank is willing to finance up to RM400,000.',
    },
    {
      term: 'MOT',
      slug: 'mot',
      definition: 'Memorandum of Transfer — the legal document that transfers registered ownership of a property from seller to buyer.',
      category: 'property',
      related: ['spa', 'valuation'],
      example: 'The MOT is typically executed after the Sale and Purchase Agreement and full payment have been completed.',
    },
    {
      term: 'SPA',
      slug: 'spa',
      definition: 'Sale and Purchase Agreement — the legal contract between buyer and seller for a property transaction, required when applying for a home loan.',
      category: 'property',
      related: ['mot', 'home-loan'],
      example: 'Banks generally require a signed SPA before finalising a home loan approval.',
    },
    {
      term: 'Valuation',
      slug: 'valuation',
      definition: "An independent assessment of a property's market value, used by banks to determine how much they are willing to finance against it.",
      category: 'property',
      related: ['ltv', 'mot'],
      example: 'If a valuation comes in below the purchase price, the loan amount the bank offers may be reduced accordingly.',
    },
    {
      term: 'Strata Title',
      slug: 'strata-title',
      definition: 'The title document for a unit in a subdivided building, such as a condominium, as distinct from a single, standalone landed title.',
      category: 'property',
      related: ['spa', 'mot'],
      example: 'Strata title for a new condominium unit is sometimes issued years after the buyer takes possession.',
    },
    {
      term: 'Vacant Possession',
      slug: 'vacant-possession',
      definition: 'The point at which a property developer hands over a completed unit to the buyer, which can affect the timing of certain loan disbursement stages.',
      category: 'property',
      related: ['spa', 'disbursement'],
      example: 'Loan disbursement for an under-construction property is often tied to progress milestones leading up to vacant possession.',
    },

    // ── General (Documents & Income) ───────────────────────────────────
    {
      term: 'Payslip',
      slug: 'payslip',
      definition: "A document from an employer showing an employee's salary, deductions, and net pay for a period — a standard income-verification document for salaried applicants.",
      category: 'general',
      related: ['ea-form', 'bank-statement'],
      example: 'Most lenders ask for your most recent payslips alongside a few months of bank statements.',
    },
    {
      term: 'EA Form',
      slug: 'ea-form',
      definition: 'A yearly statement from an employer showing total earnings and tax deductions for the year, used for income verification.',
      category: 'general',
      related: ['payslip', 'be-form'],
      example: 'Your latest EA form can help confirm a full year of income when recent payslips alone are not enough.',
    },
    {
      term: 'BE Form',
      slug: 'be-form',
      definition: 'The income tax return form for individuals with employment income in Malaysia, used by banks to verify declared income.',
      category: 'general',
      related: ['ea-form', 'borang-b'],
      example: 'A salaried employee typically files a BE form, while a business owner files a Borang B instead.',
    },
    {
      term: 'EPF Statement',
      slug: 'epf-statement',
      definition: "A statement from the Employees Provident Fund (EPF/KWSP) showing an employee's monthly contributions, used by banks to help verify employment and income.",
      category: 'general',
      related: ['kwsp', 'payslip'],
      example: 'A consistent contribution history on your EPF statement can support the income shown on your payslips.',
    },
    {
      term: 'KWSP',
      slug: 'kwsp',
      definition: "Kumpulan Wang Simpanan Pekerja — the Malay name for the Employees Provident Fund (EPF), Malaysia's retirement savings scheme for private-sector employees.",
      category: 'general',
      related: ['epf-statement', 'socso'],
      example: 'KWSP and EPF refer to the same fund and are used interchangeably in Malaysia.',
    },
    {
      term: 'SOCSO',
      slug: 'socso',
      definition: 'Social Security Organisation — provides social security protection, including injury and invalidity schemes, for Malaysian employees; contribution records can support proof of employment.',
      category: 'general',
      related: ['perkeso', 'kwsp'],
      example: 'A SOCSO contribution record alongside your payslips can help confirm continuous employment.',
    },
    {
      term: 'PERKESO',
      slug: 'perkeso',
      definition: 'Pertubuhan Keselamatan Sosial — the Malay name for SOCSO, Malaysia\'s social security organisation for employees.',
      category: 'general',
      related: ['socso', 'kwsp'],
      example: 'PERKESO and SOCSO refer to the same organisation and are used interchangeably in Malaysia.',
    },
    {
      term: 'Borang B',
      slug: 'borang-b',
      definition: 'The income tax return form for individuals with business or self-employed income, as distinct from the BE form used by salaried employees.',
      category: 'general',
      related: ['be-form', 'self-employed-income'],
      example: 'A self-employed applicant\'s latest Borang B filings are typically used in place of an EA form.',
    },
    {
      term: 'Bank Statement',
      slug: 'bank-statement',
      definition: 'A periodic record of transactions in a bank account, commonly requested to verify income, spending pattern, and overall account conduct.',
      category: 'general',
      related: ['payslip', 'self-employed-income'],
      example: 'Recent bank statements help a lender see a fuller picture of income than a payslip alone.',
    },
    {
      term: 'Permanent Employee',
      slug: 'permanent-employee',
      definition: 'An employee on an indefinite, non-fixed-term employment contract, generally viewed as a more stable income profile than fixed-term or gig work.',
      category: 'general',
      related: ['contract-employee', 'payslip'],
      example: 'A permanent employee with a long tenure at one employer often has a straightforward income profile to verify.',
    },
    {
      term: 'Contract Employee',
      slug: 'contract-employee',
      definition: 'An employee on a fixed-term employment contract. Some lenders may request the contract itself alongside payslips to confirm the remaining term of employment.',
      category: 'general',
      related: ['permanent-employee', 'payslip'],
      example: 'A contract employee nearing the end of their current term may be asked about renewal plans during assessment.',
    },
    {
      term: 'Self-employed Income',
      slug: 'self-employed-income',
      definition: 'Income from running one\'s own business rather than salaried employment, typically verified through bank statements and tax filings such as Borang B rather than a payslip.',
      category: 'general',
      related: ['borang-b', 'bank-statement', 'gig-income'],
      example: 'A sole proprietor\'s self-employed income is usually assessed over a year or two of consistent business banking activity.',
    },
    {
      term: 'Gig Income',
      slug: 'gig-income',
      definition: 'Earnings from flexible, platform-based work such as e-hailing, delivery, or freelancing, usually assessed like self-employed income because of its variable nature.',
      category: 'general',
      related: ['self-employed-income', 'bank-statement'],
      example: 'An e-hailing driver\'s gig income can be supported with several months of consistent payout records.',
    },
    {
      term: 'IC',
      slug: 'ic',
      definition: 'Kad Pengenalan (Identity Card) — Malaysia\'s national identity document, required for identity verification on every loan application.',
      category: 'general',
      related: ['mykad', 'e-kyc'],
      example: 'A copy of both sides of your IC is one of the most basic documents any lender will request.',
    },
    {
      term: 'MyKad',
      slug: 'mykad',
      definition: 'The physical chip-based identity card issued to Malaysian citizens and permanent residents — the current form of the IC.',
      category: 'general',
      related: ['ic', 'e-kyc'],
      example: 'Your MyKad is scanned as part of most e-KYC identity-verification flows.',
    },
    {
      term: 'SSM Registration',
      slug: 'ssm-registration',
      definition: 'Companies Commission of Malaysia (Suruhanjaya Syarikat Malaysia) registration documents proving that a business is legally registered.',
      category: 'general',
      related: ['form-9', 'self-employed-income'],
      example: 'A sole proprietorship\'s SSM registration is typically required alongside its owner\'s personal documents.',
    },
    {
      term: 'Form 9',
      slug: 'form-9',
      definition: "A Companies Commission of Malaysia (SSM) document, under the earlier Companies Act framework, confirming a company's registration details — used to verify business applicants.",
      category: 'general',
      related: ['ssm-registration', 'self-employed-income'],
      example: 'A lender may ask a company director for Form 9 to confirm the business is properly registered.',
    },
    {
      term: 'Auto-debit',
      slug: 'auto-debit',
      definition: 'A standing instruction that automatically deducts a loan instalment from a borrower\'s bank account on the due date, reducing the risk of missed payments.',
      category: 'general',
      related: ['installment', 'late-payment-charge'],
      example: 'Setting up auto-debit for your instalment can help you avoid late payment charges caused by simply forgetting a due date.',
    },
    {
      term: 'e-Signature',
      slug: 'e-signature',
      definition: 'A legally recognised electronic signature used to sign loan agreements and related documents online, typically as part of a digital, e-KYC-based application.',
      category: 'general',
      related: ['e-kyc', 'loan-agreement'],
      example: 'An e-signature lets you accept a letter of offer online without printing or visiting a branch.',
    },
  ],
  ms: [
    // ── Kredit ──────────────────────────────────────────────────────────
    {
      term: 'CCRIS',
      slug: 'ccris',
      definition: 'Central Credit Reference Information System — sistem yang diselenggarakan oleh Bank Negara Malaysia yang menunjukkan kemudahan kredit yang anda pegang serta tingkah laku pembayaran 12 bulan terkini seperti dilaporkan oleh bank.',
      category: 'credit',
      related: ['ctos', 'credit-score', 'credit-report'],
      example: 'Apabila anda memohon pinjaman, bank menyemak laporan CCRIS anda untuk melihat kemudahan tertunggak dan tingkah laku pembayaran terkini.',
    },
    {
      term: 'CTOS',
      slug: 'ctos',
      definition: 'Agensi pelaporan kredit swasta di Malaysia. Berbeza dengan CCRIS, laporan CTOS turut boleh merangkumi maklumat bukan perbankan seperti rekod kes undang-undang dan rujukan perdagangan.',
      category: 'credit',
      related: ['ccris', 'credit-score', 'trade-reference'],
      example: 'Kami memperoleh laporan CTOS sebagai sebahagian daripada semakan kami, sebab itulah yuran RM30 yang disebut dalam Soalan Lazim kami wujud.',
    },
    {
      term: 'Skor Kredit',
      slug: 'credit-score',
      definition: 'Ringkasan numerik kelayakan kredit, dinyatakan sebagai skor dan bukan sekadar keputusan lulus/gagal. Skala sebenar boleh berubah dari semasa ke semasa, jadi sahkan skala semasa terus dengan CTOS.',
      category: 'credit',
      related: ['ccris', 'ctos', 'credit-report'],
      example: 'Skor CTOS yang lebih tinggi umumnya memudahkan anda dipadankan dengan lebih ramai pemberi pinjaman, walaupun ia tidak pernah menjamin kelulusan.',
    },
    {
      term: 'Laporan Kredit',
      slug: 'credit-report',
      definition: 'Dokumen terperinci yang meringkaskan kemudahan kredit, sejarah pembayaran, dan sebarang rekod undang-undang berkaitan, dihimpun daripada sumber seperti CCRIS dan CTOS.',
      category: 'credit',
      related: ['ccris', 'ctos', 'credit-score'],
      example: 'Menyemak laporan kredit anda sendiri sebelum memohon boleh membantu anda mengesan dan membetulkan kesilapan lebih awal.',
    },
    {
      term: 'DSR',
      slug: 'dsr',
      definition: 'Nisbah Khidmat Hutang — peratusan pendapatan kasar bulanan yang digunakan untuk pembayaran hutang. Kebanyakan bank menggunakan garis panduan sekitar 60%, walaupun ini berbeza mengikut bank dan profil pemohon.',
      category: 'credit',
      related: ['ndi', 'akpk', 'personal-loan'],
      example: 'Jika pendapatan bulanan anda RM5,000 dan jumlah pembayaran hutang RM2,000, DSR anda lebih kurang 40%.',
    },
    {
      term: 'NDI (Pendapatan Boleh Guna Bersih)',
      slug: 'ndi',
      definition: 'Baki pendapatan selepas potongan berkanun dan pembayaran hutang sedia ada. Sesetengah bank menyemak NDI bersama DSR untuk menilai sama ada peminjam mampu menampung pinjaman baharu dengan selesa.',
      category: 'credit',
      related: ['dsr', 'akpk'],
      example: 'Peminjam bergaji tinggi tetapi NDI yang sangat rendah selepas komitmen sedia ada mungkin masih sukar untuk diluluskan.',
    },
    {
      term: 'Gagal Bayar',
      slug: 'default',
      definition: 'Kegagalan membayar balik pinjaman mengikut terma yang dipersetujui. Gagal bayar direkodkan dalam tingkah laku CCRIS anda dan boleh menyukarkan kelulusan pada masa hadapan.',
      category: 'credit',
      related: ['npl', 'credit-score'],
      example: 'Terlepas beberapa ansuran berturut-turut tanpa menghubungi bank akhirnya boleh direkodkan sebagai gagal bayar.',
    },
    {
      term: 'NPL (Pinjaman Terjejas)',
      slug: 'npl',
      definition: 'NPL (Non-Performing Loan, pinjaman terjejas) — istilah industri untuk pinjaman di mana pembayaran telah tertunggak untuk tempoh yang panjang, dianggap sebagai tanda serius pada rekod kredit.',
      category: 'credit',
      related: ['default', 'credit-score'],
      example: 'Bank memantau nisbah NPL mereka dengan teliti, salah satu sebab penajaminan boleh diperketatkan semasa tempoh ekonomi sukar.',
    },
    {
      term: 'AKPK',
      slug: 'akpk',
      definition: 'Agensi Kaunseling dan Pengurusan Kredit — agensi disokong kerajaan yang menyediakan kaunseling hutang dan pendidikan kewangan percuma kepada peminjam Malaysia.',
      category: 'credit',
      related: ['akpk-dmp', 'dsr'],
      example: 'Jika anda menghadapi beberapa hutang serentak, AKPK boleh menyemak kewangan anda dan mencadangkan jalan penyelesaian tanpa sebarang kos.',
    },
    {
      term: 'Program Pengurusan Hutang AKPK (AKPK DMP)',
      slug: 'akpk-dmp',
      definition: 'Program Pengurusan Hutang AKPK — pelan pembayaran balik berstruktur yang diaturkan oleh AKPK terus dengan bank yang menyertai apabila anda menghadapi kesukaran membayar pelbagai hutang.',
      category: 'credit',
      related: ['akpk', 'restructuring'],
      example: 'Mendaftar DMP boleh menyatukan beberapa pembayaran bank menjadi satu pelan bulanan yang lebih terurus dirunding bagi pihak anda.',
    },
    {
      term: 'Ambang Kebankrapan',
      slug: 'bankruptcy-threshold',
      definition: 'Jumlah hutang minimum yang membolehkan pemiutang memfailkan permohonan untuk mengisytiharkan penghutang bankrap di Malaysia. RM100,000 ialah ambang semasa — sahkan angka terkini kerana ambang boleh berubah dari semasa ke semasa.',
      category: 'credit',
      related: ['bankruptcy', 'default'],
      example: 'Oleh kerana ambang ini boleh disemak semula, sentiasa periksa angka semasa dan bukan bergantung pada sumber lama.',
    },
    {
      term: 'Kadar Penggunaan Kredit',
      slug: 'credit-utilization',
      definition: 'Nisbah kredit berputar yang tersedia (terutamanya kad kredit) yang sedang digunakan. Penggunaan tinggi berbanding had anda boleh dilihat kurang menggalakkan semasa penilaian.',
      category: 'credit',
      related: ['credit-score', 'dsr'],
      example: 'Menjelaskan baki kad kredit sebelum memohon boleh memperbaiki penggunaan kredit dan profil keseluruhan anda.',
    },
    {
      term: 'Rujukan Perdagangan',
      slug: 'trade-reference',
      definition: 'Rekod pembayaran bukan perbankan, seperti akaun pembekal atau perdagangan, yang mungkin dimasukkan CTOS dalam laporannya — salah satu perbezaan data CTOS berbanding data CCRIS yang tertumpu pada perbankan sahaja.',
      category: 'credit',
      related: ['ctos', 'credit-report'],
      example: 'Pemilik perniagaan dengan rujukan perdagangan yang buruk mungkin melihatnya tercermin dalam laporan CTOS mereka.',
    },

    // ── Kadar & Yuran ───────────────────────────────────────────────────
    {
      term: 'Kadar Rata',
      slug: 'flat-rate',
      definition: 'Kaedah pengiraan faedah di mana faedah dikenakan atas prinsipal asal sepanjang tempoh pinjaman, tanpa mengira berapa banyak telah dibayar balik.',
      category: 'rates',
      related: ['effective-rate', 'eir', 'personal-loan'],
      example: 'Pinjaman peribadi yang kami bantu uruskan biasanya ditawarkan dari 4.88% rata setahun, untuk tempoh sehingga 7 tahun.',
    },
    {
      term: 'Kadar Efektif',
      slug: 'effective-rate',
      definition: 'Kaedah pengiraan faedah berdasarkan baki prinsipal yang berkurangan, jadi bahagian faedah mengecil apabila anda membayar balik — sering mencerminkan kos sebenar dengan lebih tepat berbanding kadar rata.',
      category: 'rates',
      related: ['flat-rate', 'eir'],
      example: 'Kadar rata dan kadar efektif pada pinjaman yang sama boleh kelihatan serupa di atas kertas tetapi kos keseluruhannya berbeza ketara.',
    },
    {
      term: 'EIR (Kadar Faedah Efektif)',
      slug: 'eir',
      definition: 'EIR (Effective Interest Rate, kadar faedah efektif) — cara piawai untuk menyatakan kos sebenar pinjaman, termasuk faedah atas faedah (compounding), supaya pinjaman dengan struktur kadar berbeza boleh dibandingkan dengan lebih adil.',
      category: 'rates',
      related: ['flat-rate', 'effective-rate', 'apr'],
      example: 'Dua pinjaman dengan kadar rata yang sama masih boleh mempunyai EIR berbeza bergantung pada yuran dan struktur pembayaran.',
    },
    {
      term: 'APR (Kadar Peratusan Tahunan)',
      slug: 'apr',
      definition: 'APR (Annual Percentage Rate, kadar peratusan tahunan) — ukuran kadar yang boleh merangkumi yuran tertentu selain faedah. Tidak semua pemberi pinjaman di Malaysia menyatakan APR dengan cara yang sama, jadi sahkan apa yang termasuk di dalamnya.',
      category: 'rates',
      related: ['eir', 'flat-rate'],
      example: 'Minta pemberi pinjaman anda tunjukkan yuran apa, jika ada, yang dimasukkan dalam angka APR yang mereka sebut.',
    },
    {
      term: 'Kadar Asas (BR)',
      slug: 'base-rate',
      definition: 'Kadar rujukan pinjaman yang ditetapkan oleh setiap bank berdasarkan kos pembiayaan sendiri dan faktor lain; kadar sebenar peminjam biasanya Kadar Asas ditambah margin.',
      category: 'rates',
      related: ['base-lending-rate', 'opr'],
      example: 'Apabila Kadar Asas sesebuah bank meningkat, pinjaman kadar berubah yang berdasarkannya biasanya menjadi lebih mahal.',
    },
    {
      term: 'Kadar Pinjaman Asas (BLR)',
      slug: 'base-lending-rate',
      definition: 'Rangka kerja kadar rujukan lama yang mendahului sistem Kadar Asas. Sesetengah perjanjian pinjaman lama masih berdasarkan BLR dan bukan penanda aras yang lebih baharu.',
      category: 'rates',
      related: ['base-rate', 'opr'],
      example: 'Jika perjanjian pinjaman anda menyebut BLR dan bukan BR atau SBR, ia mungkin kemudahan lama dengan struktur harga berbeza.',
    },
    {
      term: 'Kadar Asas Standard (SBR)',
      slug: 'standard-base-rate',
      definition: 'Rangka kerja kadar rujukan penanda aras yang diperkenalkan oleh Bank Negara Malaysia, dipengaruhi oleh OPR, digunakan oleh bank untuk menetapkan harga bagi sesetengah pembiayaan runcit.',
      category: 'rates',
      related: ['opr', 'base-rate'],
      example: 'Perubahan pada pinjaman berkait SBR biasanya berlaku sejurus selepas perubahan pada OPR.',
    },
    {
      term: 'OPR',
      slug: 'opr',
      definition: 'OPR (Overnight Policy Rate, kadar dasar semalaman) — kadar faedah penanda aras yang ditetapkan oleh Bank Negara Malaysia yang mempengaruhi kadar pinjaman dalam ekonomi, termasuk banyak pinjaman kadar berubah.',
      category: 'rates',
      related: ['base-rate', 'standard-base-rate'],
      example: 'Apabila Bank Negara Malaysia menaikkan OPR, peminjam pinjaman kadar berubah sering melihat ansuran mereka meningkat.',
    },
    {
      term: 'Caj Pemprosesan',
      slug: 'processing-fee',
      definition: 'Caj sekali yang dikenakan oleh sesetengah pemberi pinjaman untuk memproses permohonan pinjaman. Sama ada ia dikenakan, dan berapa jumlahnya, berbeza mengikut pemberi pinjaman dan dinyatakan dalam surat tawaran bertulis.',
      category: 'rates',
      related: ['stamp-duty', 'loan-agreement'],
      example: 'Sentiasa semak surat tawaran bertulis untuk sebarang caj pemprosesan dan bukan menganggap satu peratusan tetap dikenakan.',
    },
    {
      term: 'Duti Setem',
      slug: 'stamp-duty',
      definition: 'Duti kerajaan yang dikenakan ke atas dokumen pinjaman tertentu di bawah Akta Setem. Sama ada ia dikenakan pada pinjaman anda, dan jumlahnya, dinyatakan dalam surat tawaran bertulis dan bukan satu kadar awam tetap yang anda anggap.',
      category: 'rates',
      related: ['stamp-act', 'processing-fee', 'loan-agreement'],
      example: 'Dua peminjam dengan pinjaman yang serupa mungkin melihat layanan duti setem berbeza bergantung pada produk dan dokumentasi digunakan.',
    },
    {
      term: 'Rebat Penyelesaian Awal (Peraturan 78)',
      slug: 'early-settlement-rebate',
      definition: 'Sesetengah pemberi pinjaman mengira rebet faedah untuk penyelesaian awal menggunakan kaedah jumlah-digit dikenali sebagai Peraturan 78, yang memberatkan lebih faedah pada peringkat awal pinjaman. Rebet sebenar yang anda terima bergantung pada perjanjian khusus anda.',
      category: 'rates',
      related: ['settlement', 'lock-in-period'],
      example: 'Menyelesaikan pinjaman pada tahun pertama di bawah struktur Peraturan 78 biasanya menghasilkan rebet lebih kecil berbanding menyelesaikannya menjelang akhir tempoh.',
    },
    {
      term: 'Caj Bayaran Lewat',
      slug: 'late-payment-charge',
      definition: 'Caj yang dikenakan apabila ansuran tidak dibayar menjelang tarikh matangnya, seperti dinyatakan dalam perjanjian pinjaman. Bayaran lewat juga boleh direkodkan dalam tingkah laku CCRIS anda.',
      category: 'rates',
      related: ['ccris', 'loan-agreement'],
      example: 'Menyediakan arahan debit auto adalah satu cara peminjam cuba mengelakkan caj bayaran lewat.',
    },
    {
      term: 'Tempoh Kunci Masuk',
      slug: 'lock-in-period',
      definition: 'Tempoh di mana penyelesaian atau pembiayaan semula pinjaman lebih awal mencetuskan penalti di bawah perjanjian. Terma dan tempoh berbeza mengikut pemberi pinjaman dan produk.',
      category: 'rates',
      related: ['early-settlement-rebate', 'refinancing'],
      example: 'Semak sama ada pinjaman rumah anda masih dalam tempoh kunci masuk sebelum memohon pembiayaan semula di tempat lain.',
    },
    {
      term: 'Tempoh Tangguh',
      slug: 'grace-period',
      definition: 'Tempoh singkat, jika ditawarkan oleh pemberi pinjaman, selepas tarikh matang atau selepas pengeluaran dana di mana tiada caj lewat dikenakan. Ia tidak dijamin pada setiap produk pinjaman.',
      category: 'rates',
      related: ['late-payment-charge', 'moratorium'],
      example: 'Tempoh tangguh yang singkat boleh memberi peminjam beberapa hari tambahan untuk membuat bayaran tanpa dikenakan caj lewat.',
    },

    // ── Produk Pinjaman ─────────────────────────────────────────────────
    {
      term: 'Pinjaman Peribadi',
      slug: 'personal-loan',
      definition: 'Pinjaman tanpa cagaran untuk kegunaan peribadi seperti kecemasan, bil perubatan, atau menyatukan hutang lain. Pinjaman peribadi yang kami bantu uruskan sehingga RM100,000, sepanjang 1 hingga 7 tahun, dari 4.88% rata setahun.',
      category: 'products',
      related: ['flat-rate', 'dsr', 'unsecured-loan'],
      example: 'Pinjaman peribadi tidak memerlukan anda mencagarkan sebarang aset, tetapi kelulusan masih bergantung pada pendapatan dan profil kredit anda.',
    },
    {
      term: 'Pinjaman Perniagaan',
      slug: 'business-loan',
      definition: 'Pembiayaan untuk perusahaan kecil dan sederhana atau syarikat, umumnya dinilai berdasarkan aliran tunai perniagaan dan, untuk sesetengah produk, cagaran, bukan slip gaji peribadi sahaja.',
      category: 'products',
      related: ['collateral', 'dsr'],
      example: 'Peniaga runcit mungkin menggunakan pinjaman perniagaan untuk membiayai inventori menjelang musim perayaan.',
    },
    {
      term: 'Pinjaman Kereta',
      slug: 'car-loan',
      definition: 'Pembiayaan untuk membeli kenderaan, biasanya distruktur sebagai sewa beli, di mana pemberi pembiayaan mengekalkan kepentingan ke atas kenderaan sehingga ansuran terakhir dibayar.',
      category: 'products',
      related: ['hire-purchase', 'collateral'],
      example: 'Kebanyakan pinjaman kereta di Malaysia diaturkan melalui perjanjian sewa beli dan bukan pinjaman peribadi tanpa cagaran.',
    },
    {
      term: 'Sewa Beli',
      slug: 'hire-purchase',
      definition: 'Pengaturan pembiayaan, biasa digunakan untuk kenderaan, di mana anda membayar secara ansuran sambil menggunakan aset. Pemilikan hanya berpindah kepada anda selepas semua bayaran selesai.',
      category: 'products',
      related: ['car-loan', 'collateral'],
      example: 'Di bawah sewa beli, pemberi pembiayaan secara teknikal mengekalkan kepentingan ke atas kereta sehingga ansuran terakhir jelas.',
    },
    {
      term: 'Pinjaman Rumah',
      slug: 'home-loan',
      definition: 'Pinjaman bercagar untuk membeli hartanah, dengan hartanah itu sendiri berfungsi sebagai cagaran. Pinjaman ini biasanya mempunyai tempoh lebih panjang berbanding pembiayaan peribadi.',
      category: 'products',
      related: ['mrta', 'ltv', 'collateral'],
      example: 'Jumlah pinjaman rumah yang diluluskan biasanya dihadkan oleh had LTV hartanah serta DSR anda.',
    },
    {
      term: 'Pinjaman Bercagar',
      slug: 'secured-loan',
      definition: 'Pinjaman yang disokong oleh cagaran. Jika peminjam gagal membayar balik, pemberi pinjaman mungkin boleh merampas aset yang dicagarkan mengikut proses yang dinyatakan dalam perjanjian.',
      category: 'products',
      related: ['collateral', 'unsecured-loan', 'home-loan'],
      example: 'Pinjaman rumah dan kebanyakan pinjaman kereta adalah pinjaman bercagar, kerana hartanah atau kenderaan menyokong pembiayaan itu.',
    },
    {
      term: 'Pinjaman Tanpa Cagaran',
      slug: 'unsecured-loan',
      definition: 'Pinjaman yang tidak disokong oleh sebarang cagaran, bergantung sepenuhnya pada pendapatan dan profil kredit peminjam. Pinjaman peribadi biasanya tanpa cagaran.',
      category: 'products',
      related: ['personal-loan', 'secured-loan'],
      example: 'Oleh kerana tiada aset menyokong pinjaman tanpa cagaran, pemberi pinjaman umumnya lebih menitikberatkan pendapatan dan rekod CCRIS/CTOS.',
    },
    {
      term: 'Pembiayaan Semula',
      slug: 'refinancing',
      definition: 'Menggantikan pinjaman sedia ada dengan yang baharu, biasanya untuk mendapatkan terma lebih baik seperti kadar lebih rendah atau tempoh berbeza.',
      category: 'products',
      related: ['home-loan', 'lock-in-period'],
      example: 'Peminjam mungkin membiayai semula pinjaman rumah untuk memanfaatkan kadar semasa yang lebih rendah, tertakluk kepada sebarang tempoh kunci masuk.',
    },
    {
      term: 'Penyatuan Hutang',
      slug: 'debt-consolidation',
      definition: 'Menggabungkan beberapa hutang sedia ada menjadi satu pinjaman baharu dengan satu ansuran bulanan, yang boleh memudahkan pembayaran balik dan, bergantung pada terma baharu, mengubah jumlah perbelanjaan bulanan keseluruhan.',
      category: 'products',
      related: ['personal-loan', 'dsr'],
      example: 'Menyatukan tiga hutang berasingan menjadi satu pinjaman boleh memudahkan anda menjejak satu tarikh matang setiap bulan.',
    },
    {
      term: 'Pinjaman Tambahan',
      slug: 'top-up-loan',
      definition: 'Pembiayaan tambahan yang ditambah di atas pinjaman sedia ada, biasanya pinjaman rumah, biasanya dicagarkan dengan cagaran yang sama dan tertakluk kepada kelulusan bank yang baharu.',
      category: 'products',
      related: ['home-loan', 'collateral'],
      example: 'Pemilik rumah mungkin memohon pinjaman tambahan terhadap pinjaman rumah sedia ada untuk membiayai kerja ubah suai.',
    },
    {
      term: 'Pemindahan Baki',
      slug: 'balance-transfer',
      definition: 'Memindahkan baki tertunggak, seperti hutang kad kredit, kepada kemudahan baharu, kadangkala pada kadar promosi untuk tempoh terhad. Terma berbeza mengikut penerbit kad.',
      category: 'products',
      related: ['debt-consolidation', 'effective-rate'],
      example: 'Pemindahan baki boleh mengurangkan kos faedah buat sementara waktu, tetapi semak kadar yang berkuat kuasa selepas tempoh promosi tamat.',
    },
    {
      term: 'Penjamin',
      slug: 'guarantor',
      definition: 'Seseorang yang bersetuju membayar balik pinjaman jika peminjam utama tidak dapat berbuat demikian. Penjamin hanya bertanggungjawab apabila peminjam gagal bayar, berbeza dengan peminjam bersama.',
      category: 'products',
      related: ['joint-borrower', 'credit-score'],
      example: 'Mempunyai penjamin dengan profil kredit yang kukuh kadangkala boleh membantu permohonan yang sebaliknya berada di tahap sederhana.',
    },
    {
      term: 'Peminjam Bersama',
      slug: 'joint-borrower',
      definition: 'Pemohon yang memohon bersama peminjam utama dan berkongsi tanggungjawab pembayaran balik sepenuhnya secara berterusan, berbeza dengan penjamin yang hanya bertindak apabila berlaku gagal bayar.',
      category: 'products',
      related: ['guarantor', 'dsr'],
      example: 'Memohon bersama peminjam bersama boleh menggabungkan dua pendapatan, yang mungkin membantu memenuhi keperluan DSR bank.',
    },
    {
      term: 'Cagaran',
      slug: 'collateral',
      definition: 'Aset yang dicagarkan sebagai jaminan untuk pinjaman. Jika peminjam gagal bayar, pemberi pinjaman mungkin mengambil tindakan terhadap cagaran mengikut proses yang dinyatakan dalam perjanjian.',
      category: 'products',
      related: ['secured-loan', 'foreclosure'],
      example: 'Hartanah dan kenderaan adalah bentuk cagaran paling biasa dalam pemberian pinjaman pengguna di Malaysia.',
    },
    {
      term: 'Pinjaman Kecemasan',
      slug: 'emergency-loan',
      definition: 'Pembiayaan peribadi bertindak balas pantas untuk perbelanjaan mendesak, umumnya mengikut piawaian kelayakan dan dokumentasi yang sama seperti pinjaman peribadi lain.',
      category: 'products',
      related: ['personal-loan', 'dsr'],
      example: 'Pinjaman kecemasan boleh membantu menampung bil perubatan yang tidak dijangka sementara anda menguruskan kewangan jangka panjang.',
    },

    // ── Proses & Terma ──────────────────────────────────────────────────
    {
      term: 'Pengeluaran Dana',
      slug: 'disbursement',
      definition: 'Pengeluaran dana pinjaman yang diluluskan kepada peminjam, biasanya dibayar terus ke akaun bank sebaik sahaja tawaran diterima. Masa berbeza mengikut pemberi pinjaman dan produk.',
      category: 'process',
      related: ['letter-of-offer', 'settlement'],
      example: 'Bagi sesetengah pinjaman hartanah, pengeluaran dana berlaku secara berperingkat mengikut kemajuan pembinaan dan bukan sekali gus.',
    },
    {
      term: 'Tempoh Menyejuk (Cooling-off)',
      slug: 'cooling-off',
      definition: 'Tempoh singkat selepas menandatangani di mana sesetengah perjanjian membenarkan peminjam membatalkan tanpa penalti, jika kontrak khusus itu memperuntukkannya — semak tawaran anda sendiri kerana ia tidak automatik pada setiap pinjaman.',
      category: 'process',
      related: ['loan-agreement', 'letter-of-offer'],
      example: 'Sesetengah perjanjian produk merangkumi tempoh menyejuk yang singkat; minta pemberi pinjaman anda sahkan sebelum anda menandatangani.',
    },
    {
      term: 'e-KYC',
      slug: 'e-kyc',
      definition: 'e-KYC (Electronic Know-Your-Customer, pengesahan pelanggan elektronik) — proses pengesahan identiti digital, sering menggabungkan swafoto dengan imbasan IC, yang membolehkan pemohon mendaftar tanpa melawat cawangan secara fizikal.',
      category: 'process',
      related: ['ic', 'mykad', 'e-signature'],
      example: 'e-KYC membolehkan anda mengesahkan identiti dari rumah tanpa perlu melawat kaunter cawangan.',
    },
    {
      term: 'Pengamortisasian',
      slug: 'amortization',
      definition: 'Proses mengagihkan pembayaran balik pinjaman sepanjang tempoh masa. Jadual amortisasi menunjukkan cara setiap ansuran dibahagikan antara prinsipal dan faedah sepanjang tempoh.',
      category: 'process',
      related: ['principal', 'installment', 'tenure'],
      example: 'Pada peringkat awal pinjaman berjadual amortisasi, bahagian yang lebih besar dalam setiap ansuran biasanya pergi kepada faedah dan bukan prinsipal.',
    },
    {
      term: 'Tempoh',
      slug: 'tenure',
      definition: 'Jangka masa yang anda ada untuk membayar balik pinjaman. Tempoh lebih panjang umumnya menurunkan ansuran bulanan tetapi meningkatkan jumlah faedah dibayar sepanjang hayat pinjaman.',
      category: 'process',
      related: ['installment', 'amortization'],
      example: 'Tempoh pinjaman peribadi biasanya berjalan dari 1 hingga 7 tahun, manakala pinjaman rumah boleh jauh lebih panjang.',
    },
    {
      term: 'Moratorium',
      slug: 'moratorium',
      definition: 'Penangguhan atau penggantungan sementara ansuran pinjaman yang mungkin diberikan oleh pemberi pinjaman semasa tempoh kesukaran. Ketersediaan, tempoh, dan terma ditentukan oleh setiap bank.',
      category: 'process',
      related: ['restructuring', 'rescheduling'],
      example: 'Moratorium yang singkat boleh memberi ruang bernafas kepada peminjam selepas kehilangan pendapatan secara tiba-tiba, jika bank bersetuju memberikannya.',
    },
    {
      term: 'Penstrukturan Semula',
      slug: 'restructuring',
      definition: 'Perubahan terma pinjaman yang diluluskan oleh pemberi pinjaman, seperti tempoh atau kadar, dipersetujui mengikut kes bagi peminjam yang menghadapi kesukaran kewangan sebenar.',
      category: 'process',
      related: ['moratorium', 'rescheduling', 'akpk-dmp'],
      example: 'Penstrukturan semula mungkin melanjutkan tempoh pinjaman untuk menurunkan ansuran bulanan ke tahap yang lebih terurus.',
    },
    {
      term: 'Penjadualan Semula',
      slug: 'rescheduling',
      definition: 'Melaraskan jadual pembayaran balik pinjaman sedia ada, seperti mengagihkan baki bayaran sepanjang tempoh lebih panjang, biasanya untuk mengurangkan jumlah ansuran.',
      category: 'process',
      related: ['restructuring', 'moratorium'],
      example: 'Penjadualan semula pinjaman boleh menurunkan komitmen bulanan, walaupun ia mungkin meningkatkan jumlah faedah dibayar keseluruhannya.',
    },
    {
      term: 'Surat Tawaran',
      slug: 'letter-of-offer',
      definition: 'Dokumen rasmi daripada bank mengesahkan jumlah pinjaman diluluskan, kadar, tempoh, dan semua terma serta yuran berkaitan. Menandatanganinya mengikat anda kepada pinjaman itu.',
      category: 'process',
      related: ['loan-agreement', 'disbursement'],
      example: 'Baca setiap baris surat tawaran, termasuk jadual yuran, sebelum menandatanganinya.',
    },
    {
      term: 'Prinsipal',
      slug: 'principal',
      definition: 'Jumlah asal yang dipinjam, tidak termasuk faedah dan yuran. Setiap ansuran membayar sebahagian prinsipal dan sebahagian faedah.',
      category: 'process',
      related: ['installment', 'amortization'],
      example: 'Membuat bayaran tambahan terhadap prinsipal boleh memendekkan baki tempoh pinjaman.',
    },
    {
      term: 'Ansuran',
      slug: 'installment',
      definition: 'Setiap bayaran berkala yang dijadualkan, biasanya bulanan, yang meliputi sebahagian prinsipal dan sebahagian faedah di bawah pinjaman berjadual amortisasi.',
      category: 'process',
      related: ['principal', 'tenure'],
      example: 'Tempoh lebih panjang mengagihkan prinsipal yang sama merentasi lebih banyak ansuran yang lebih kecil.',
    },
    {
      term: 'Perjanjian Pinjaman',
      slug: 'loan-agreement',
      definition: 'Kontrak mengikat yang menetapkan prinsipal, kadar, tempoh, yuran, dan syarat yang mentadbir pinjaman. Baca sepenuhnya sebelum menandatangani.',
      category: 'process',
      related: ['letter-of-offer', 'stamp-duty'],
      example: 'Sebarang yuran yang hanya disebut secara lisan masih perlu tercatat secara bertulis dalam perjanjian pinjaman sebelum anda menandatangani.',
    },
    {
      term: 'Penyelesaian',
      slug: 'settlement',
      definition: 'Pembayaran balik penuh baki tertunggak pinjaman, sama ada pada akhir tempoh atau lebih awal daripada jadual.',
      category: 'process',
      related: ['early-settlement-rebate', 'disbursement'],
      example: 'Meminta angka penyelesaian daripada bank anda memberitahu jumlah tepat yang perlu dibayar untuk menutup pinjaman hari ini.',
    },

    // ── Undang-undang & Pematuhan ───────────────────────────────────────
    {
      term: 'PDPA',
      slug: 'pdpa',
      definition: 'Akta Perlindungan Data Peribadi 2010 — undang-undang Malaysia yang mentadbir cara organisasi boleh mengumpul, menggunakan, menyimpan, dan mendedahkan data peribadi, termasuk maklumat peminjam.',
      category: 'legal',
      related: ['e-kyc', 'bank-statement'],
      example: 'Pemberi pinjaman perlu menerangkan, selaras dengan PDPA, cara penyata bank yang anda hantar akan disimpan dan digunakan.',
    },
    {
      term: 'Akta Pemberi Pinjam Wang 1951',
      slug: 'moneylenders-act-1951',
      definition: 'Undang-undang di mana pemberi pinjam wang berlesen di Malaysia dikawal selia, dengan pelesenan dan penguatkuasaan diselia oleh KPKT.',
      category: 'legal',
      related: ['kpkt-licence', 'ah-long'],
      example: 'Pemberi pinjam wang yang beroperasi tanpa lesen di bawah Akta Pemberi Pinjam Wang 1951 bertindak secara haram.',
    },
    {
      term: 'Lesen KPKT',
      slug: 'kpkt-licence',
      definition: 'Lesen yang dikeluarkan di bawah Akta Pemberi Pinjam Wang 1951 oleh Kementerian Pembangunan Kerajaan Tempatan (KPKT), diperlukan untuk beroperasi secara sah sebagai pemberi pinjam wang di Malaysia.',
      category: 'legal',
      related: ['moneylenders-act-1951', 'loan-shark-red-flags'],
      example: 'Anda boleh meminta mana-mana pemberi pinjam wang berlesen berkongsi butiran pelesenan KPKT mereka melalui saluran rasmi.',
    },
    {
      term: 'Ah Long',
      slug: 'ah-long',
      definition: 'Istilah kolokial untuk pemberi pinjaman haram tanpa lesen ("loan shark"). Berurusan dengan Ah Long membawa risiko kewangan dan peribadi yang serius, termasuk gangguan.',
      category: 'legal',
      related: ['loan-shark-red-flags', 'moneylenders-act-1951'],
      example: 'Mangsa gangguan Ah Long digalakkan membuat laporan polis dan bukan terus membayar.',
    },
    {
      term: 'Tanda Amaran Along',
      slug: 'loan-shark-red-flags',
      definition: 'Tanda amaran pemberian pinjaman haram, seperti tiada perjanjian bertulis, yuran "buka kunci" pendahuluan, ugutan, atau hubungan hanya melalui saluran tidak rasmi. Pemberi pinjaman berlesen yang sah menyatakan terma secara bertulis.',
      category: 'legal',
      related: ['ah-long', 'kpkt-licence'],
      example: 'Diminta membayar yuran pendahuluan sebelum sebarang semakan dijalankan ialah tanda amaran along yang klasik.',
    },
    {
      term: 'Kebankrapan',
      slug: 'bankruptcy',
      definition: 'Status undang-undang di mana seseorang diisytiharkan tidak mampu membayar hutangnya. Di Malaysia, kebankrapan menyekat aktiviti seperti mendapatkan kredit baharu atau memegang jawatan pengarah syarikat.',
      category: 'legal',
      related: ['bankruptcy-threshold', 'default'],
      example: 'Diisytiharkan bankrap boleh menjejaskan keupayaan anda untuk melancong ke luar negara atau memegang jawatan profesional tertentu.',
    },
    {
      term: 'Rampasan Hartanah (Foreclosure)',
      slug: 'foreclosure',
      definition: 'Proses undang-undang di mana pemberi pinjaman mengambil milikan cagaran, seperti hartanah, apabila peminjam gagal membayar balik pinjaman bercagar — umumnya pilihan terakhir.',
      category: 'legal',
      related: ['collateral', 'secured-loan'],
      example: 'Bank biasanya meneroka pilihan penstrukturan semula bersama peminjam yang menghadapi kesukaran jauh sebelum memulakan rampasan hartanah.',
    },
    {
      term: 'Akta Setem',
      slug: 'stamp-act',
      definition: 'Perundangan yang mentadbir duti setem ke atas dokumen, termasuk perjanjian pinjaman. Jumlah yang perlu dibayar untuk pinjaman anda, jika ada, dinyatakan dalam surat tawaran bertulis dan bukan satu kadar awam tetap yang anda anggap.',
      category: 'legal',
      related: ['stamp-duty', 'loan-agreement'],
      example: 'Minta pemberi pinjaman anda tunjukkan item duti setem yang tepat dalam tawaran anda dan bukan menganggarkannya sendiri.',
    },

    // ── Pembiayaan Islam ────────────────────────────────────────────────
    {
      term: 'Murabahah',
      slug: 'murabahah',
      definition: 'Struktur jual beli yang menambah margin keuntungan di atas kos, di mana pemberi pembiayaan membeli aset lalu menjualnya semula kepada pelanggan pada harga margin yang didedahkan, dibayar secara ansuran.',
      category: 'islamic',
      related: ['shariah-compliant', 'profit-rate'],
      example: 'Sesetengah produk pembiayaan peribadi Islam di Malaysia menggunakan struktur Murabahah dan bukan pinjaman konvensional berasaskan faedah.',
    },
    {
      term: 'Tawarruq',
      slug: 'tawarruq',
      definition: 'Struktur pembiayaan berasaskan komoditi yang melibatkan jualan dan jualan semula aset asas untuk menjana tunai bagi pelanggan, diaturkan supaya patuh Shariah.',
      category: 'islamic',
      related: ['shariah-compliant', 'murabahah'],
      example: 'Tawarruq biasa digunakan untuk menstruktur pembiayaan peribadi dan kad kredit Islam di Malaysia.',
    },
    {
      term: "Bai' Al-Inah",
      slug: 'bai-al-inah',
      definition: "Struktur jual kemudian beli semula yang digunakan dalam sesetengah produk pembiayaan Islam. Keharusannya diperdebatkan dalam kalangan ulama di bidang kuasa berbeza, jadi terma tepat berbeza mengikut institusi.",
      category: 'islamic',
      related: ['shariah-compliant', 'tawarruq'],
      example: "Tanya bank anda struktur mana — Bai' Al-Inah, Tawarruq, atau lain — yang mendasari produk Islam tertentu sebelum membandingkannya.",
    },
    {
      term: 'Ijarah',
      slug: 'ijarah',
      definition: 'Struktur berasaskan sewaan di mana pemberi pembiayaan memiliki aset dan menyewakannya kepada pelanggan untuk bayaran sewa (keuntungan), biasa digunakan dalam sewa beli dan pembiayaan hartanah Islam.',
      category: 'islamic',
      related: ['shariah-compliant', 'profit-rate'],
      example: 'Struktur Ijarah sering digunakan untuk pembiayaan kenderaan dan rumah Islam di Malaysia.',
    },
    {
      term: 'Takaful',
      slug: 'takaful',
      definition: 'Alternatif patuh Shariah kepada insurans konvensional, berdasarkan sumbangan bersama dan perkongsian risiko dalam kalangan peserta.',
      category: 'islamic',
      related: ['shariah-compliant', 'mrta'],
      example: 'Pelan Takaful boleh memainkan peranan perlindungan yang serupa dengan MRTA bagi peminjam yang lebih suka pilihan patuh Shariah.',
    },
    {
      term: 'Patuh Shariah',
      slug: 'shariah-compliant',
      definition: 'Menggambarkan produk kewangan yang distruktur untuk mematuhi undang-undang Islam, mengelakkan faedah (riba) demi struktur perkongsian keuntungan atau berasaskan yuran yang diselia oleh jawatankuasa Shariah.',
      category: 'islamic',
      related: ['islamic-financing', 'profit-rate'],
      example: 'Pinjaman patuh Shariah menggantikan kadar faedah dengan kadar keuntungan yang didedahkan di bawah struktur kontrak yang diluluskan.',
    },
    {
      term: 'Kadar Keuntungan',
      slug: 'profit-rate',
      definition: 'Persamaan kadar faedah dalam pembiayaan Islam — pulangan yang diperoleh pemberi pembiayaan di bawah struktur patuh Shariah seperti Murabahah atau Ijarah.',
      category: 'islamic',
      related: ['shariah-compliant', 'murabahah'],
      example: 'Membandingkan kadar keuntungan merentasi produk Islam berfungsi hampir sama seperti membandingkan kadar faedah pada pinjaman konvensional.',
    },
    {
      term: 'Pembiayaan Islam',
      slug: 'islamic-financing',
      definition: 'Istilah payung untuk produk pembiayaan patuh Shariah. Ketersediaan bergantung pada bank dan produk tertentu pada masa anda memohon — tanya kami dan kami akan sahkan apa yang ditawarkan pada masa ini.',
      category: 'islamic',
      related: ['shariah-compliant', 'murabahah', 'ijarah'],
      example: 'Pembiayaan Islam tersedia untuk sesetengah, tetapi tidak semestinya semua, produk pinjaman yang kami bantu uruskan.',
    },
    {
      term: 'Wakalah',
      slug: 'wakalah',
      definition: 'Kontrak agensi di mana satu pihak (ejen) bertindak bagi pihak-pihak lain (prinsipal), digunakan dalam sesetengah struktur pembiayaan Islam dan Takaful.',
      category: 'islamic',
      related: ['shariah-compliant', 'takaful'],
      example: 'Susunan Wakalah mungkin melantik bank sebagai ejen untuk menjalankan transaksi bagi pihak pelanggan.',
    },
    {
      term: 'Musyarakah Mutanaqisah',
      slug: 'musyarakah-mutanaqisah',
      definition: 'Struktur perkongsian berkurangan, biasa dalam pembiayaan rumah Islam, di mana bank dan pelanggan sama-sama memiliki aset dan pelanggan secara beransur-ansur membeli bahagian bank dari semasa ke semasa.',
      category: 'islamic',
      related: ['ijarah', 'home-loan', 'shariah-compliant'],
      example: 'Di bawah Musyarakah Mutanaqisah, setiap ansuran meningkatkan bahagian pemilikan pelanggan dalam hartanah itu.',
    },

    // ── Hartanah ─────────────────────────────────────────────────────────
    {
      term: 'MRTA',
      slug: 'mrta',
      definition: 'MRTA (Mortgage Reducing Term Assurance, insurans berjangka menurun untuk gadai janji) — melindungi baki tertunggak pinjaman rumah jika peminjam meninggal dunia atau hilang upaya kekal.',
      category: 'property',
      related: ['mlta', 'home-loan'],
      example: 'Perlindungan MRTA biasanya berkurangan lebih kurang selaras dengan baki tertunggak pinjaman rumah anda dari semasa ke semasa.',
    },
    {
      term: 'MLTA',
      slug: 'mlta',
      definition: 'MLTA (Mortgage Level Term Assurance, insurans berjangka tetap untuk gadai janji) — berbeza dengan MRTA, ini mengekalkan jumlah perlindungan tetap sepanjang tempoh pinjaman, umumnya dengan kos lebih tinggi tetapi perlindungan yang lebih konsisten.',
      category: 'property',
      related: ['mrta', 'home-loan'],
      example: 'Peminjam yang mahu perlindungan kekal walaupun baki pinjaman menurun mungkin memilih MLTA berbanding MRTA.',
    },
    {
      term: 'LTV / Margin Pembiayaan',
      slug: 'ltv',
      definition: 'Loan-to-Value — jumlah pinjaman dinyatakan sebagai peratusan nilai hartanah atau harga belian, mana yang lebih rendah. Had maksimum berbeza mengikut bank dan jenis hartanah.',
      category: 'property',
      related: ['home-loan', 'valuation'],
      example: 'LTV 80% pada hartanah bernilai RM500,000 bermaksud bank sanggup membiayai sehingga RM400,000.',
    },
    {
      term: 'MOT (Memorandum Pindah Milik)',
      slug: 'mot',
      definition: 'MOT (Memorandum of Transfer, memorandum pindah milik) — dokumen undang-undang yang memindahkan pemilikan berdaftar hartanah daripada penjual kepada pembeli.',
      category: 'property',
      related: ['spa', 'valuation'],
      example: 'MOT biasanya dilaksanakan selepas Perjanjian Jual Beli dan pembayaran penuh selesai.',
    },
    {
      term: 'SPA (Perjanjian Jual Beli)',
      slug: 'spa',
      definition: 'SPA (Sale and Purchase Agreement, perjanjian jual beli) — kontrak undang-undang antara pembeli dan penjual untuk transaksi hartanah, diperlukan apabila memohon pinjaman rumah.',
      category: 'property',
      related: ['mot', 'home-loan'],
      example: 'Bank umumnya memerlukan SPA yang ditandatangani sebelum memuktamadkan kelulusan pinjaman rumah.',
    },
    {
      term: 'Penilaian',
      slug: 'valuation',
      definition: 'Penilaian bebas terhadap nilai pasaran hartanah, digunakan oleh bank untuk menentukan berapa banyak mereka sanggup biayai terhadapnya.',
      category: 'property',
      related: ['ltv', 'mot'],
      example: 'Jika penilaian datang lebih rendah daripada harga belian, jumlah pinjaman yang ditawarkan bank mungkin dikurangkan.',
    },
    {
      term: 'Hakmilik Strata',
      slug: 'strata-title',
      definition: 'Dokumen hakmilik bagi unit dalam bangunan yang dipecah bahagi, seperti kondominium, berbeza dengan hakmilik tanah tunggal yang berasingan.',
      category: 'property',
      related: ['spa', 'mot'],
      example: 'Hakmilik strata bagi unit kondominium baharu kadangkala dikeluarkan bertahun-tahun selepas pembeli mengambil milikan.',
    },
    {
      term: 'Milikan Kosong',
      slug: 'vacant-possession',
      definition: 'Titik di mana pemaju hartanah menyerahkan unit siap kepada pembeli, yang boleh mempengaruhi masa peringkat pengeluaran dana pinjaman tertentu.',
      category: 'property',
      related: ['spa', 'disbursement'],
      example: 'Pengeluaran dana pinjaman untuk hartanah dalam pembinaan sering dikaitkan dengan pencapaian kemajuan menjelang milikan kosong.',
    },

    // ── Dokumen & Pendapatan ────────────────────────────────────────────
    {
      term: 'Slip Gaji',
      slug: 'payslip',
      definition: 'Dokumen daripada majikan yang menunjukkan gaji, potongan, dan bayaran bersih pekerja bagi sesuatu tempoh — dokumen pengesahan pendapatan piawai bagi pemohon bergaji.',
      category: 'general',
      related: ['ea-form', 'bank-statement'],
      example: 'Kebanyakan pemberi pinjaman meminta slip gaji terkini anda bersama beberapa bulan penyata bank.',
    },
    {
      term: 'Borang EA',
      slug: 'ea-form',
      definition: 'Penyata tahunan daripada majikan yang menunjukkan jumlah pendapatan dan potongan cukai untuk tahun tersebut, digunakan untuk pengesahan pendapatan.',
      category: 'general',
      related: ['payslip', 'be-form'],
      example: 'Borang EA terkini anda boleh membantu mengesahkan pendapatan setahun penuh apabila slip gaji terkini sahaja tidak mencukupi.',
    },
    {
      term: 'Borang BE',
      slug: 'be-form',
      definition: 'Borang penyata pemulangan cukai pendapatan bagi individu berpendapatan penggajian di Malaysia, digunakan oleh bank untuk mengesahkan pendapatan yang diisytiharkan.',
      category: 'general',
      related: ['ea-form', 'borang-b'],
      example: 'Pekerja bergaji biasanya memfailkan Borang BE, manakala pemilik perniagaan memfailkan Borang B sebaliknya.',
    },
    {
      term: 'Penyata EPF',
      slug: 'epf-statement',
      definition: 'Penyata daripada Kumpulan Wang Simpanan Pekerja (EPF/KWSP) yang menunjukkan caruman bulanan pekerja, digunakan oleh bank untuk membantu mengesahkan pekerjaan dan pendapatan.',
      category: 'general',
      related: ['kwsp', 'payslip'],
      example: 'Sejarah caruman yang konsisten pada penyata EPF anda boleh menyokong pendapatan yang ditunjukkan pada slip gaji anda.',
    },
    {
      term: 'KWSP',
      slug: 'kwsp',
      definition: 'Kumpulan Wang Simpanan Pekerja — nama Bahasa Melayu bagi Employees Provident Fund (EPF), skim simpanan persaraan Malaysia untuk pekerja sektor swasta.',
      category: 'general',
      related: ['epf-statement', 'socso'],
      example: 'KWSP dan EPF merujuk kepada kumpulan wang yang sama dan digunakan secara bertukar ganti di Malaysia.',
    },
    {
      term: 'SOCSO',
      slug: 'socso',
      definition: 'SOCSO (Social Security Organisation, Pertubuhan Keselamatan Sosial) — menyediakan perlindungan keselamatan sosial, termasuk skim kecederaan dan hilang upaya, untuk pekerja Malaysia; rekod caruman boleh menyokong bukti pekerjaan.',
      category: 'general',
      related: ['perkeso', 'kwsp'],
      example: 'Rekod caruman SOCSO bersama slip gaji anda boleh membantu mengesahkan pekerjaan berterusan.',
    },
    {
      term: 'PERKESO',
      slug: 'perkeso',
      definition: 'Pertubuhan Keselamatan Sosial — nama Bahasa Melayu bagi SOCSO, organisasi keselamatan sosial Malaysia untuk pekerja.',
      category: 'general',
      related: ['socso', 'kwsp'],
      example: 'PERKESO dan SOCSO merujuk kepada organisasi yang sama dan digunakan secara bertukar ganti di Malaysia.',
    },
    {
      term: 'Borang B',
      slug: 'borang-b',
      definition: 'Borang penyata pemulangan cukai pendapatan bagi individu berpendapatan perniagaan atau bekerja sendiri, berbeza dengan Borang BE yang digunakan oleh pekerja bergaji.',
      category: 'general',
      related: ['be-form', 'self-employed-income'],
      example: 'Fail Borang B terkini pemohon bekerja sendiri biasanya digunakan sebagai ganti Borang EA.',
    },
    {
      term: 'Penyata Bank',
      slug: 'bank-statement',
      definition: 'Rekod berkala transaksi dalam akaun bank, biasanya diminta untuk mengesahkan pendapatan, corak perbelanjaan, dan tingkah laku akaun keseluruhan.',
      category: 'general',
      related: ['payslip', 'self-employed-income'],
      example: 'Penyata bank terkini membantu pemberi pinjaman melihat gambaran pendapatan yang lebih lengkap berbanding slip gaji sahaja.',
    },
    {
      term: 'Pekerja Tetap',
      slug: 'permanent-employee',
      definition: 'Pekerja dengan kontrak pekerjaan tanpa had masa tetap, umumnya dilihat sebagai profil pendapatan lebih stabil berbanding kerja bertempoh tetap atau gig.',
      category: 'general',
      related: ['contract-employee', 'payslip'],
      example: 'Pekerja tetap dengan tempoh perkhidmatan lama di satu majikan sering mempunyai profil pendapatan yang mudah disahkan.',
    },
    {
      term: 'Pekerja Kontrak',
      slug: 'contract-employee',
      definition: 'Pekerja dengan kontrak pekerjaan bertempoh tetap. Sesetengah pemberi pinjaman mungkin meminta kontrak itu sendiri bersama slip gaji untuk mengesahkan baki tempoh pekerjaan.',
      category: 'general',
      related: ['permanent-employee', 'payslip'],
      example: 'Pekerja kontrak yang hampir tamat tempoh semasa mungkin ditanya tentang rancangan pembaharuan semasa penilaian.',
    },
    {
      term: 'Pendapatan Bekerja Sendiri',
      slug: 'self-employed-income',
      definition: 'Pendapatan daripada menjalankan perniagaan sendiri dan bukan pekerjaan bergaji, biasanya disahkan melalui penyata bank dan penyata cukai seperti Borang B dan bukan slip gaji.',
      category: 'general',
      related: ['borang-b', 'bank-statement', 'gig-income'],
      example: 'Pendapatan bekerja sendiri pemilik tunggal biasanya dinilai sepanjang setahun atau dua tahun aktiviti perbankan perniagaan yang konsisten.',
    },
    {
      term: 'Pendapatan Ekonomi Gig',
      slug: 'gig-income',
      definition: 'Pendapatan daripada kerja fleksibel berasaskan platform seperti e-hailing, penghantaran, atau kerja bebas, biasanya dinilai seperti pendapatan bekerja sendiri kerana sifatnya yang berubah-ubah.',
      category: 'general',
      related: ['self-employed-income', 'bank-statement'],
      example: 'Pendapatan ekonomi gig pemandu e-hailing boleh disokong dengan beberapa bulan rekod bayaran yang konsisten.',
    },
    {
      term: 'IC (Kad Pengenalan)',
      slug: 'ic',
      definition: 'Kad Pengenalan — dokumen pengenalan diri kebangsaan Malaysia, diperlukan untuk pengesahan identiti pada setiap permohonan pinjaman.',
      category: 'general',
      related: ['mykad', 'e-kyc'],
      example: 'Salinan kedua-dua belah IC anda adalah antara dokumen paling asas yang akan diminta mana-mana pemberi pinjaman.',
    },
    {
      term: 'MyKad',
      slug: 'mykad',
      definition: 'Kad pengenalan berasaskan cip fizikal yang dikeluarkan kepada warganegara dan pemastautin tetap Malaysia — bentuk semasa IC.',
      category: 'general',
      related: ['ic', 'e-kyc'],
      example: 'MyKad anda diimbas sebagai sebahagian daripada kebanyakan aliran pengesahan identiti e-KYC.',
    },
    {
      term: 'Pendaftaran SSM',
      slug: 'ssm-registration',
      definition: 'Dokumen pendaftaran Suruhanjaya Syarikat Malaysia (SSM) yang membuktikan sesebuah perniagaan berdaftar secara sah.',
      category: 'general',
      related: ['form-9', 'self-employed-income'],
      example: 'Pendaftaran SSM bagi pemilikan tunggal biasanya diperlukan bersama dokumen peribadi pemiliknya.',
    },
    {
      term: 'Borang 9',
      slug: 'form-9',
      definition: 'Dokumen Suruhanjaya Syarikat Malaysia (SSM), di bawah rangka kerja Akta Syarikat terdahulu, mengesahkan butiran pendaftaran syarikat — digunakan untuk mengesahkan pemohon perniagaan.',
      category: 'general',
      related: ['ssm-registration', 'self-employed-income'],
      example: 'Pemberi pinjaman mungkin meminta Borang 9 daripada pengarah syarikat untuk mengesahkan perniagaan berdaftar dengan betul.',
    },
    {
      term: 'Debit Auto',
      slug: 'auto-debit',
      definition: 'Arahan tetap yang secara automatik menolak ansuran pinjaman daripada akaun bank peminjam pada tarikh matang, mengurangkan risiko terlepas bayaran.',
      category: 'general',
      related: ['installment', 'late-payment-charge'],
      example: 'Menyediakan debit auto untuk ansuran anda boleh membantu anda mengelakkan caj bayaran lewat akibat terlupa tarikh matang.',
    },
    {
      term: 'Tandatangan Elektronik',
      slug: 'e-signature',
      definition: 'Tandatangan elektronik yang diiktiraf secara sah untuk menandatangani perjanjian pinjaman dan dokumen berkaitan dalam talian, biasanya sebagai sebahagian daripada permohonan digital berasaskan e-KYC.',
      category: 'general',
      related: ['e-kyc', 'loan-agreement'],
      example: 'Tandatangan elektronik membolehkan anda menerima surat tawaran dalam talian tanpa mencetak atau melawat cawangan.',
    },
  ],
};

/** Per-language UI copy object handed to the glossary page's client component. */
export type GlossaryUi = (typeof glossaryUi)[keyof typeof glossaryUi];
