export interface GlossaryTerm {
  term: string;
  definition: string;
  category: string;
  related?: string[];
  example?: string;
}

export const glossaryUi = {
  en: {
    breadcrumbHome: 'Home',
    breadcrumbGlossary: 'Glossary',
    title: 'Financial Glossary',
    subtitle: 'Understanding loan and credit terminology',
    lede: 'A comprehensive guide to financial terms commonly used in Malaysia. Search or browse by category to understand the language of loans and credit.',
    searchPlaceholder: 'Search terms...',
    allCategories: 'All',
    categories: {
      credit: 'Credit & Scoring',
      loans: 'Loan Types',
      rates: 'Rates & Fees',
      documents: 'Documents',
      banking: 'Banking Terms',
      legal: 'Legal Terms',
    },
    showMore: 'Show More',
    showLess: 'Show Less',
    relatedTerms: 'Related Terms',
    example: 'Example',
    quickNav: {
      title: 'Quick Navigation',
      subtitle: 'Jump to a section',
    },
    noResults: 'No terms found. Try a different search.',
  },
  ms: {
    breadcrumbHome: 'Utama',
    breadcrumbGlossary: 'Glosari',
    title: 'Glosari Kewangan',
    subtitle: 'Memahami terminologi pinjaman dan kredit',
    lede: 'Panduan komprehensif istilah kewangan yang biasa digunakan di Malaysia. Cari atau layari mengikut kategori untuk memahami bahasa pinjaman dan kredit.',
    searchPlaceholder: 'Cari istilah...',
    allCategories: 'Semua',
    categories: {
      credit: 'Kredit & Skor',
      loans: 'Jenis Pinjaman',
      rates: 'Kadar & Caj',
      documents: 'Dokumen',
      banking: 'Istilah Perbankan',
      legal: 'Istilah Undang-undang',
    },
    showMore: 'Tunjuk Lagi',
    showLess: 'Tunjuk Kurang',
    relatedTerms: 'Istilah Berkaitan',
    example: 'Contoh',
    quickNav: {
      title: 'Navigasi Pantas',
      subtitle: 'Lompat ke bahagian',
    },
    noResults: 'Tiada istilah dijumpai. Cuba carian lain.',
  },
} as const;

export const glossaryTerms: { en: GlossaryTerm[]; ms: GlossaryTerm[] } = {
  en: [
    {
      term: 'CCRIS',
      definition: 'Central Credit Reference Information System - A system maintained by Bank Negara Malaysia that contains credit information of borrowers from financial institutions. It shows your credit history, outstanding loans, and payment behavior for the past 12 months.',
      category: 'credit',
      related: ['CTOS', 'Credit Score', 'Credit Report'],
      example: 'When you apply for a loan, banks check your CCRIS report to see if you have any outstanding loans or late payments.',
    },
    {
      term: 'CTOS',
      definition: 'Credit Tip-Off Service - A private credit reporting agency in Malaysia that provides credit reports and scores. Unlike CCRIS, CTOS also includes non-banking information such as legal cases, directorship information, and trade references.',
      category: 'credit',
      related: ['CCRIS', 'Credit Score', 'Credit Report'],
      example: 'A CTOS report might show if you have any pending legal cases or have been a director of a company that was wound up.',
    },
    {
      term: 'Credit Score',
      definition: 'A numerical representation of your creditworthiness based on your credit history. In Malaysia, CTOS scores range from 300-850, with higher scores indicating better credit. Banks use this to assess your loan eligibility.',
      category: 'credit',
      related: ['CCRIS', 'CTOS', 'Credit Report'],
      example: 'A credit score of 750 or above is generally considered excellent and gives you access to the best loan rates.',
    },
    {
      term: 'Credit Report',
      definition: 'A detailed document showing your credit history, including all loans, credit cards, payment history, and any legal issues. This is what banks review when processing your loan application.',
      category: 'credit',
      related: ['CCRIS', 'CTOS', 'Credit Score'],
    },
    {
      term: 'DSR',
      definition: 'Debt Service Ratio - The percentage of your monthly income used to pay debts. Calculated by dividing your total monthly debt payments by your gross monthly income. Most banks require DSR below 60-70%.',
      category: 'credit',
      related: ['Net Income', 'Gross Income'],
      example: 'If your monthly income is RM5,000 and your total debt payments are RM2,000, your DSR is 40%.',
    },
    {
      term: 'Default',
      definition: 'Failure to repay a loan according to the agreed terms. This negatively impacts your credit score and may result in legal action. A default record stays on your credit report for years.',
      category: 'credit',
      related: ['NPL', 'Credit Score'],
    },
    {
      term: 'NPL',
      definition: 'Non-Performing Loan - A loan where the borrower has failed to make payments for 90 days or more. This is a serious mark on your credit record.',
      category: 'credit',
      related: ['Default', 'Credit Score'],
    },
    {
      term: 'Personal Loan',
      definition: 'An unsecured loan for personal use such as emergencies, medical bills, or debt consolidation. No collateral required, but interest rates are typically higher than secured loans.',
      category: 'loans',
      related: ['Secured Loan', 'Unsecured Loan'],
      example: 'You can get a personal loan of up to RM100,000 without pledging any assets.',
    },
    {
      term: 'Hire Purchase',
      definition: 'A financing arrangement commonly used for vehicles where you pay in installments while using the asset. The ownership transfers to you only after all payments are completed.',
      category: 'loans',
      related: ['Car Loan', 'Collateral'],
      example: 'When you buy a car through hire purchase, the bank technically owns the car until you make the final payment.',
    },
    {
      term: 'Home Loan / Mortgage',
      definition: 'A secured loan specifically for purchasing property. The property serves as collateral. These loans typically have the longest tenure (up to 35 years) and lowest interest rates.',
      category: 'loans',
      related: ['Collateral', 'Secured Loan', 'MRTA'],
    },
    {
      term: 'Refinancing',
      definition: 'Replacing an existing loan with a new one, usually to get better terms such as lower interest rates or longer tenure. Common for home loans and car loans.',
      category: 'loans',
      related: ['Home Loan', 'Interest Rate'],
      example: 'If interest rates drop, you might refinance your home loan to reduce your monthly payments.',
    },
    {
      term: 'Debt Consolidation',
      definition: 'Combining multiple debts into a single loan with one monthly payment. This can simplify debt management and potentially reduce overall interest costs.',
      category: 'loans',
      related: ['Personal Loan', 'DSR'],
    },
    {
      term: 'Secured Loan',
      definition: 'A loan backed by collateral (an asset). If you fail to repay, the lender can seize the collateral. These loans typically have lower interest rates.',
      category: 'loans',
      related: ['Collateral', 'Unsecured Loan', 'Home Loan'],
    },
    {
      term: 'Unsecured Loan',
      definition: 'A loan not backed by any collateral. The lender relies solely on your creditworthiness. Personal loans are typically unsecured.',
      category: 'loans',
      related: ['Personal Loan', 'Secured Loan'],
    },
    {
      term: 'Flat Rate',
      definition: 'An interest calculation method where interest is calculated on the original principal throughout the loan tenure, regardless of how much has been repaid.',
      category: 'rates',
      related: ['Reducing Balance', 'EIR'],
      example: 'A 5% flat rate on a RM10,000 loan means you pay RM500 interest per year for the entire tenure.',
    },
    {
      term: 'Reducing Balance / Effective Rate',
      definition: 'An interest calculation method where interest is calculated on the remaining principal balance. As you pay down the loan, your interest portion decreases.',
      category: 'rates',
      related: ['Flat Rate', 'EIR'],
      example: 'Home loans typically use reducing balance, so your interest charges decrease as you pay down the principal.',
    },
    {
      term: 'EIR',
      definition: 'Effective Interest Rate - The true cost of borrowing that accounts for compounding and all fees. This allows you to compare loans with different rate structures.',
      category: 'rates',
      related: ['Flat Rate', 'Reducing Balance', 'APR'],
    },
    {
      term: 'BLR / BR',
      definition: 'Base Lending Rate / Base Rate - The reference rate set by banks for pricing loans. Your actual rate is typically BLR/BR plus a margin.',
      category: 'rates',
      related: ['OPR', 'Interest Rate'],
    },
    {
      term: 'OPR',
      definition: 'Overnight Policy Rate - The interest rate set by Bank Negara Malaysia that influences all lending rates in the economy. Changes to OPR affect variable-rate loans.',
      category: 'rates',
      related: ['BLR', 'Interest Rate'],
    },
    {
      term: 'Processing Fee',
      definition: 'A one-time fee charged by lenders to cover the administrative costs of processing your loan application. Usually 1-2% of the loan amount.',
      category: 'rates',
      related: ['Stamp Duty', 'Legal Fees'],
    },
    {
      term: 'Stamp Duty',
      definition: "A government tax on loan documents. For loans, it's typically 0.5% of the loan amount. This is a mandatory cost when taking any loan.",
      category: 'rates',
      related: ['Processing Fee', 'Legal Fees'],
    },
    {
      term: 'Early Settlement Penalty',
      definition: 'A fee charged if you pay off your loan before the agreed tenure. Usually applies to the first few years of the loan. Check your loan agreement for specific terms.',
      category: 'rates',
      related: ['Refinancing', 'Lock-in Period'],
    },
    {
      term: 'Lock-in Period',
      definition: 'A period during which you cannot refinance or fully settle the loan without incurring a penalty. Common in home loans, typically 3-5 years.',
      category: 'rates',
      related: ['Early Settlement Penalty', 'Refinancing'],
    },
    {
      term: 'EPF Statement',
      definition: 'A statement from the Employees Provident Fund showing your monthly contributions. Banks use this to verify your employment and income.',
      category: 'documents',
      related: ['Payslip', 'EA Form'],
    },
    {
      term: 'EA Form',
      definition: 'A yearly statement from your employer showing your total earnings and tax deductions for the year. Required for income verification.',
      category: 'documents',
      related: ['EPF Statement', 'BE Form'],
    },
    {
      term: 'BE Form',
      definition: 'The income tax return form for individuals with employment income in Malaysia. Used by banks to verify your declared income.',
      category: 'documents',
      related: ['EA Form', 'Tax Return'],
    },
    {
      term: 'SPA',
      definition: 'Sale and Purchase Agreement - A legal contract between buyer and seller for property transactions. Required when applying for a home loan.',
      category: 'documents',
      related: ['Home Loan', 'Strata Title'],
    },
    {
      term: 'SSM Registration',
      definition: 'Companies Commission of Malaysia (Suruhanjaya Syarikat Malaysia) registration documents proving your business is legally registered.',
      category: 'documents',
      related: ['Business Loan', 'Form 9'],
    },
    {
      term: 'Principal',
      definition: 'The original amount borrowed, excluding interest and fees. Your monthly payments consist of principal repayment plus interest.',
      category: 'banking',
      related: ['Interest', 'Installment'],
    },
    {
      term: 'Tenure',
      definition: 'The length of time you have to repay the loan. Longer tenures mean lower monthly payments but higher total interest paid.',
      category: 'banking',
      related: ['Installment', 'Interest'],
      example: 'A home loan might have a tenure of 30 years, while a personal loan typically has 1-7 years.',
    },
    {
      term: 'Collateral',
      definition: 'An asset pledged as security for a loan. If you default, the lender can seize the collateral. Common collateral includes property and vehicles.',
      category: 'banking',
      related: ['Secured Loan', 'Default'],
    },
    {
      term: 'Guarantor',
      definition: 'A person who agrees to repay your loan if you cannot. Having a guarantor can help you get approved for loans you might not qualify for alone.',
      category: 'banking',
      related: ['Joint Application', 'Credit Score'],
    },
    {
      term: 'Disbursement',
      definition: 'The release of loan funds to you or directly to the seller/dealer. For property, disbursement follows the construction progress.',
      category: 'banking',
      related: ['Principal', 'Settlement'],
    },
    {
      term: 'Amortization',
      definition: 'The process of spreading loan payments over time. An amortization schedule shows how each payment is split between principal and interest.',
      category: 'banking',
      related: ['Principal', 'Interest', 'Tenure'],
    },
    {
      term: 'MRTA',
      definition: 'Mortgage Reducing Term Assurance - A decreasing term insurance that covers your outstanding home loan if you pass away or become permanently disabled.',
      category: 'legal',
      related: ['MLTA', 'Home Loan'],
    },
    {
      term: 'MLTA',
      definition: 'Mortgage Level Term Assurance - Unlike MRTA, this maintains a fixed coverage amount throughout the loan tenure. More expensive but provides consistent protection.',
      category: 'legal',
      related: ['MRTA', 'Home Loan'],
    },
    {
      term: 'Letter of Offer',
      definition: 'A formal document from the bank stating the approved loan amount, interest rate, tenure, and all terms and conditions. Signing this commits you to the loan.',
      category: 'legal',
      related: ['Loan Agreement', 'Disbursement'],
    },
    {
      term: 'Bankruptcy',
      definition: 'A legal status where a person is declared unable to pay their debts. In Malaysia, bankruptcy affects your ability to get credit, be a company director, and more.',
      category: 'legal',
      related: ['Default', 'NPL'],
    },
    {
      term: 'Foreclosure',
      definition: 'The legal process where a lender takes possession of a property when the borrower fails to make payments. This is a last resort for secured loans.',
      category: 'legal',
      related: ['Default', 'Collateral', 'Home Loan'],
    },
  ],
  ms: [
    {
      term: 'CCRIS',
      definition: 'Central Credit Reference Information System - Sistem yang diselenggarakan oleh Bank Negara Malaysia yang mengandungi maklumat kredit peminjam dari institusi kewangan. Ia menunjukkan sejarah kredit, pinjaman tertunggak, dan tingkah laku pembayaran untuk 12 bulan lepas.',
      category: 'credit',
      related: ['CTOS', 'Skor Kredit', 'Laporan Kredit'],
      example: 'Apabila anda memohon pinjaman, bank menyemak laporan CCRIS anda untuk melihat jika ada pinjaman tertunggak atau pembayaran lewat.',
    },
    {
      term: 'CTOS',
      definition: 'Credit Tip-Off Service - Agensi pelaporan kredit swasta di Malaysia yang menyediakan laporan dan skor kredit. Tidak seperti CCRIS, CTOS juga merangkumi maklumat bukan perbankan seperti kes undang-undang dan maklumat pengarah.',
      category: 'credit',
      related: ['CCRIS', 'Skor Kredit', 'Laporan Kredit'],
      example: 'Laporan CTOS mungkin menunjukkan jika anda mempunyai kes undang-undang yang belum selesai.',
    },
    {
      term: 'Skor Kredit',
      definition: 'Perwakilan numerik kelayakan kredit anda berdasarkan sejarah kredit. Di Malaysia, skor CTOS berkisar 300-850, dengan skor lebih tinggi menunjukkan kredit lebih baik.',
      category: 'credit',
      related: ['CCRIS', 'CTOS', 'Laporan Kredit'],
      example: 'Skor kredit 750 atau lebih dianggap cemerlang dan memberi akses kepada kadar pinjaman terbaik.',
    },
    {
      term: 'DSR',
      definition: 'Nisbah Khidmat Hutang - Peratusan pendapatan bulanan yang digunakan untuk membayar hutang. Dikira dengan membahagikan jumlah bayaran hutang bulanan dengan pendapatan kasar bulanan.',
      category: 'credit',
      related: ['Pendapatan Bersih', 'Pendapatan Kasar'],
      example: 'Jika pendapatan bulanan anda RM5,000 dan jumlah bayaran hutang RM2,000, DSR anda adalah 40%.',
    },
    {
      term: 'Pinjaman Peribadi',
      definition: 'Pinjaman tanpa cagaran untuk kegunaan peribadi seperti kecemasan, bil perubatan, atau penggabungan hutang. Tiada cagaran diperlukan.',
      category: 'loans',
      related: ['Pinjaman Bercagar', 'Pinjaman Tanpa Cagaran'],
      example: 'Anda boleh mendapat pinjaman peribadi sehingga RM100,000 tanpa mencagarkan sebarang aset.',
    },
    {
      term: 'Sewa Beli',
      definition: 'Pengaturan pembiayaan yang biasa digunakan untuk kenderaan di mana anda membayar secara ansuran sambil menggunakan aset. Pemilikan dipindahkan kepada anda hanya selepas semua bayaran selesai.',
      category: 'loans',
      related: ['Pinjaman Kereta', 'Cagaran'],
      example: 'Apabila anda membeli kereta melalui sewa beli, bank secara teknikal memiliki kereta sehingga anda membuat bayaran terakhir.',
    },
    {
      term: 'Pinjaman Rumah / Gadai Janji',
      definition: 'Pinjaman bercagar khusus untuk membeli hartanah. Hartanah berfungsi sebagai cagaran. Pinjaman ini biasanya mempunyai tempoh terpanjang dan kadar faedah terendah.',
      category: 'loans',
      related: ['Cagaran', 'Pinjaman Bercagar', 'MRTA'],
    },
    {
      term: 'Pembiayaan Semula',
      definition: 'Menggantikan pinjaman sedia ada dengan yang baru, biasanya untuk mendapat terma lebih baik seperti kadar faedah lebih rendah atau tempoh lebih panjang.',
      category: 'loans',
      related: ['Pinjaman Rumah', 'Kadar Faedah'],
      example: 'Jika kadar faedah turun, anda mungkin membiayai semula pinjaman rumah untuk mengurangkan bayaran bulanan.',
    },
    {
      term: 'Kadar Rata',
      definition: 'Kaedah pengiraan faedah di mana faedah dikira pada prinsipal asal sepanjang tempoh pinjaman, tanpa mengira berapa banyak telah dibayar.',
      category: 'rates',
      related: ['Baki Berkurangan', 'EIR'],
      example: 'Kadar rata 5% pada pinjaman RM10,000 bermaksud anda membayar faedah RM500 setahun untuk keseluruhan tempoh.',
    },
    {
      term: 'Baki Berkurangan',
      definition: 'Kaedah pengiraan faedah di mana faedah dikira pada baki prinsipal yang tinggal. Apabila anda membayar pinjaman, bahagian faedah anda berkurangan.',
      category: 'rates',
      related: ['Kadar Rata', 'EIR'],
      example: 'Pinjaman rumah biasanya menggunakan baki berkurangan, jadi caj faedah anda berkurangan apabila anda membayar prinsipal.',
    },
    {
      term: 'OPR',
      definition: 'Kadar Dasar Semalaman - Kadar faedah yang ditetapkan oleh Bank Negara Malaysia yang mempengaruhi semua kadar pinjaman dalam ekonomi.',
      category: 'rates',
      related: ['BLR', 'Kadar Faedah'],
    },
    {
      term: 'Caj Pemprosesan',
      definition: 'Caj sekali yang dikenakan oleh pemberi pinjaman untuk menampung kos pentadbiran memproses permohonan pinjaman anda. Biasanya 1-2% daripada jumlah pinjaman.',
      category: 'rates',
      related: ['Duti Setem', 'Yuran Guaman'],
    },
    {
      term: 'Duti Setem',
      definition: 'Cukai kerajaan ke atas dokumen pinjaman. Untuk pinjaman, biasanya 0.5% daripada jumlah pinjaman. Ini adalah kos wajib apabila mengambil sebarang pinjaman.',
      category: 'rates',
      related: ['Caj Pemprosesan', 'Yuran Guaman'],
    },
    {
      term: 'Penyata EPF',
      definition: 'Penyata dari Kumpulan Wang Simpanan Pekerja yang menunjukkan caruman bulanan anda. Bank menggunakan ini untuk mengesahkan pekerjaan dan pendapatan anda.',
      category: 'documents',
      related: ['Slip Gaji', 'Borang EA'],
    },
    {
      term: 'Borang EA',
      definition: 'Penyata tahunan dari majikan menunjukkan jumlah pendapatan dan potongan cukai untuk tahun tersebut. Diperlukan untuk pengesahan pendapatan.',
      category: 'documents',
      related: ['Penyata EPF', 'Borang BE'],
    },
    {
      term: 'SPA',
      definition: 'Perjanjian Jual Beli - Kontrak undang-undang antara pembeli dan penjual untuk transaksi hartanah. Diperlukan apabila memohon pinjaman rumah.',
      category: 'documents',
      related: ['Pinjaman Rumah', 'Hakmilik Strata'],
    },
    {
      term: 'Prinsipal',
      definition: 'Jumlah asal yang dipinjam, tidak termasuk faedah dan caj. Bayaran bulanan anda terdiri daripada bayaran balik prinsipal ditambah faedah.',
      category: 'banking',
      related: ['Faedah', 'Ansuran'],
    },
    {
      term: 'Tempoh',
      definition: 'Jangka masa anda perlu membayar balik pinjaman. Tempoh lebih panjang bermaksud bayaran bulanan lebih rendah tetapi jumlah faedah lebih tinggi.',
      category: 'banking',
      related: ['Ansuran', 'Faedah'],
      example: 'Pinjaman rumah mungkin mempunyai tempoh 30 tahun, manakala pinjaman peribadi biasanya 1-7 tahun.',
    },
    {
      term: 'Cagaran',
      definition: 'Aset yang dicagarkan sebagai jaminan untuk pinjaman. Jika anda gagal bayar, pemberi pinjaman boleh merampas cagaran.',
      category: 'banking',
      related: ['Pinjaman Bercagar', 'Gagal Bayar'],
    },
    {
      term: 'Penjamin',
      definition: 'Seseorang yang bersetuju membayar pinjaman anda jika anda tidak dapat. Mempunyai penjamin boleh membantu anda diluluskan untuk pinjaman.',
      category: 'banking',
      related: ['Permohonan Bersama', 'Skor Kredit'],
    },
    {
      term: 'MRTA',
      definition: 'Mortgage Reducing Term Assurance - Insurans berjangka berkurangan yang melindungi pinjaman rumah tertunggak anda jika anda meninggal dunia atau hilang upaya kekal.',
      category: 'legal',
      related: ['MLTA', 'Pinjaman Rumah'],
    },
    {
      term: 'Surat Tawaran',
      definition: 'Dokumen rasmi dari bank menyatakan jumlah pinjaman yang diluluskan, kadar faedah, tempoh, dan semua terma dan syarat.',
      category: 'legal',
      related: ['Perjanjian Pinjaman', 'Pengeluaran'],
    },
    {
      term: 'Kebankrapan',
      definition: 'Status undang-undang di mana seseorang diisytiharkan tidak mampu membayar hutang mereka. Di Malaysia, kebankrapan menjejaskan keupayaan anda mendapat kredit.',
      category: 'legal',
      related: ['Gagal Bayar', 'NPL'],
    },
  ],
};
