export const guideUi = {
  en: {
    home: 'Home',
    guides: 'Loan Guides',
    steps: 'Steps',
    checklist: 'Checklist',
    warnings: 'Watch out for',
    faq: 'Questions',
    related: 'Useful next reads',
    eyebrow: 'Loan guide',
    moreQuestions: 'More questions',
    viewAllFaqs: 'View all FAQs',
  },
  ms: {
    home: 'Utama',
    guides: 'Panduan Pinjaman',
    steps: 'Langkah',
    checklist: 'Senarai semak',
    warnings: 'Perkara yang perlu diawasi',
    faq: 'Soalan',
    related: 'Bacaan seterusnya',
    eyebrow: 'Panduan pinjaman',
    moreQuestions: 'Soalan lanjut',
    viewAllFaqs: 'Lihat semua Soalan Lazim',
  },
} as const;
