export type GuideTopic = {
  slug: string;
  title: string;
  titleMs: string;
  description: string;
  descriptionMs: string;
  stats: { label: string; labelMs: string; value: string }[];
  stepsTitle: string;
  stepsTitleMs: string;
  steps: { title: string; titleMs: string; description: string; descriptionMs: string }[];
  checklistTitle: string;
  checklistTitleMs: string;
  checklist: string[];
  checklistMs: string[];
  warningsTitle: string;
  warningsTitleMs: string;
  warnings: string[];
  warningsMs: string[];
  faqs: { question: string; questionMs: string; answer: string; answerMs: string }[];
  related: { title: string; titleMs: string; href: string }[];
};

export const guideTopics: GuideTopic[] = [
  {
    slug: 'personal-loan-minimum-salary',
    title: 'Personal Loan Minimum Salary in Malaysia',
    titleMs: 'Gaji Minimum Pinjaman Peribadi di Malaysia',
    description: 'A practical guide to what salary bands typically support small, medium, or larger personal loan requests before existing commitments are counted.',
    descriptionMs: 'Panduan praktikal tentang julat gaji yang biasanya menyokong permohonan pinjaman peribadi kecil, sederhana, atau lebih besar sebelum komitmen sedia ada dikira.',
    stats: [
      { label: 'Common starting band', labelMs: 'Julat permulaan biasa', value: 'RM2k-RM3k' },
      { label: 'Safer DSR target', labelMs: 'Sasaran DSR lebih selamat', value: '< 60%' },
      { label: 'Better file window', labelMs: 'Tetingkap fail lebih baik', value: '3 clean cycles' },
      { label: 'Best first step', labelMs: 'Langkah pertama terbaik', value: 'Check salary vs debt' },
    ],
    stepsTitle: 'How to judge your salary band properly',
    stepsTitleMs: 'Cara menilai julat gaji anda dengan betul',
    steps: [
      { title: 'Start with net income, not gross headline salary', titleMs: 'Mulakan dengan pendapatan bersih, bukan gaji kasar', description: 'Lenders care about what remains after deductions and ongoing commitments.', descriptionMs: 'Lender mengambil kira baki selepas potongan dan komitmen berterusan.' },
      { title: 'Add card minimums and instalments first', titleMs: 'Masukkan minimum kad dan ansuran dahulu', description: 'Salary alone is not enough when existing debts already consume most monthly capacity.', descriptionMs: 'Gaji sahaja tidak mencukupi apabila hutang sedia ada sudah menggunakan kebanyakan kapasiti bulanan.' },
      { title: 'Match the amount request to your band', titleMs: 'Padankan jumlah diminta dengan julat anda', description: 'Borrowers are often declined because the requested amount is unrealistic for the income and file quality.', descriptionMs: 'Ramai peminjam ditolak kerana jumlah diminta tidak realistik untuk tahap pendapatan dan kualiti fail.' },
      { title: 'Use cleaner documents to improve lender comfort', titleMs: 'Gunakan dokumen lebih kemas untuk menaikkan keyakinan lender', description: 'Stable salary credits and lower utilization can make the same income look stronger.', descriptionMs: 'Kredit gaji yang stabil dan utilization lebih rendah boleh membuat pendapatan yang sama kelihatan lebih kuat.' },
    ],
    checklistTitle: 'What to prepare',
    checklistTitleMs: 'Apa yang perlu disediakan',
    checklist: ['Latest payslips', 'Recent bank statements', 'List of all loan and card commitments', 'Target amount and preferred tenure'],
    checklistMs: ['Slip gaji terkini', 'Penyata bank terkini', 'Senarai semua komitmen pinjaman dan kad', 'Jumlah sasaran dan tempoh pilihan'],
    warningsTitle: 'Common mistakes',
    warningsTitleMs: 'Kesilapan biasa',
    warnings: ['Requesting an amount based on gross pay only', 'Ignoring card minimums', 'Applying repeatedly after one decline', 'Using outdated income documents'],
    warningsMs: ['Meminta jumlah berdasarkan gaji kasar sahaja', 'Mengabaikan minimum kad', 'Memohon berulang kali selepas satu penolakan', 'Menggunakan dokumen pendapatan yang lama'],
    faqs: [
      { question: 'Can RM3,000 salary still qualify?', questionMs: 'Gaji RM3,000 masih boleh layak?', answer: 'Sometimes yes, if commitments are low and the requested amount is reasonable.', answerMs: 'Kadang-kadang boleh, jika komitmen rendah dan jumlah diminta munasabah.' },
      { question: 'Does higher salary always solve approval?', questionMs: 'Gaji lebih tinggi sentiasa menyelesaikan kelulusan?', answer: 'No. File quality, commitments, and documentation still matter.', answerMs: 'Tidak. Kualiti fail, komitmen, dan dokumentasi tetap penting.' },
      { question: 'Should I lower the amount before reapplying?', questionMs: 'Patutkah saya rendahkan jumlah sebelum mohon semula?', answer: 'Often yes, especially when affordability is the main blocker.', answerMs: 'Selalunya ya, terutamanya jika kemampuan ansuran ialah halangan utama.' },
    ],
    related: [
      { title: 'Eligibility test', titleMs: 'Ujian kelayakan', href: '/eligibility-test' },
      { title: 'Loan rejection recovery guide', titleMs: 'Panduan pulih selepas ditolak', href: '/loan-guides/loan-rejection-recovery' },
      { title: 'Personal loan guide', titleMs: 'Panduan pinjaman peribadi', href: '/loans/personal' },
    ],
  },
  {
    slug: 'personal-loan-documents-checklist',
    title: 'Personal Loan Documents Checklist Malaysia',
    titleMs: 'Senarai Semak Dokumen Pinjaman Peribadi Malaysia',
    description: 'A deeper document-readiness guide showing which files lenders usually want first, which gaps create delays, and how to prepare a cleaner submission pack.',
    descriptionMs: 'Panduan kesiapsiagaan dokumen yang lebih mendalam tentang fail yang biasanya diminta lender dahulu, jurang yang menyebabkan kelewatan, dan cara menyediakan pakej penghantaran yang lebih kemas.',
    stats: [
      { label: 'Best statement window', labelMs: 'Tempoh penyata terbaik', value: '3-6 months' },
      { label: 'Priority items', labelMs: 'Item keutamaan', value: 'Income + bank' },
      { label: 'Frequent delay', labelMs: 'Kelewatan kerap', value: 'Missing proof' },
      { label: 'Submission goal', labelMs: 'Matlamat penghantaran', value: 'Cleaner first pass' },
    ],
    stepsTitle: 'How to prepare a cleaner file',
    stepsTitleMs: 'Cara menyediakan fail yang lebih kemas',
    steps: [
      { title: 'Start with identity and income', titleMs: 'Mulakan dengan identiti dan pendapatan', description: 'Core ID and income documents usually determine whether the file can move at all.', descriptionMs: 'Dokumen identiti dan pendapatan teras biasanya menentukan sama ada fail boleh bergerak atau tidak.' },
      { title: 'Pair income with bank evidence', titleMs: 'Padankan pendapatan dengan bukti bank', description: 'A payslip without matching credits often creates more questions than confidence.', descriptionMs: 'Slip gaji tanpa kredit yang sepadan sering menimbulkan lebih banyak soalan daripada keyakinan.' },
      { title: 'Explain unusual movements early', titleMs: 'Jelaskan pergerakan luar biasa lebih awal', description: 'Large transfers, cash deposits, or irregular credits should make sense in the file.', descriptionMs: 'Pindahan besar, deposit tunai, atau kredit tidak teratur perlu masuk akal dalam fail.' },
      { title: 'Keep one consistent pack ready', titleMs: 'Simpan satu pakej yang konsisten', description: 'Scattered versions and mixed dates are one of the easiest ways to slow down review.', descriptionMs: 'Versi bertabur dan tarikh bercampur adalah antara cara paling mudah untuk melambatkan semakan.' },
    ],
    checklistTitle: 'Priority documents',
    checklistTitleMs: 'Dokumen keutamaan',
    checklist: ['IC or identification', 'Payslips or income proof', 'Bank statements', 'EPF or tax support where relevant'],
    checklistMs: ['IC atau pengenalan diri', 'Slip gaji atau bukti pendapatan', 'Penyata bank', 'EPF atau sokongan cukai jika berkaitan'],
    warningsTitle: 'What slows reviews down',
    warningsTitleMs: 'Apa yang melambatkan semakan',
    warnings: ['Missing statement pages', 'Unreadable screenshots', 'Income that cannot be traced in bank statements', 'Using old documents after circumstances changed'],
    warningsMs: ['Halaman penyata yang hilang', 'Tangkapan layar yang tidak jelas', 'Pendapatan yang tidak boleh dikesan dalam penyata bank', 'Menggunakan dokumen lama selepas keadaan berubah'],
    faqs: [
      { question: 'Do I need EPF for every application?', questionMs: 'Perlu EPF untuk setiap permohonan?', answer: 'Not always, but it often helps for salaried borrowers because it supports employment consistency.', answerMs: 'Tidak semestinya, tetapi ia sering membantu untuk peminjam bergaji kerana menyokong konsistensi pekerjaan.' },
      { question: 'Can screenshots replace PDF statements?', questionMs: 'Boleh tangkapan layar ganti PDF penyata?', answer: 'Only sometimes. Cleaner bank statements are usually easier to assess and trust.', answerMs: 'Kadang-kadang sahaja. Penyata bank yang lebih kemas biasanya lebih mudah dinilai dan dipercayai.' },
      { question: 'Should I send everything at once?', questionMs: 'Patutkah saya hantar semua sekali gus?', answer: 'Send the core pack first and keep supporting files ready. That usually creates a cleaner workflow.', answerMs: 'Hantar pakej teras dahulu dan simpan fail sokongan sedia. Itu biasanya menghasilkan aliran kerja yang lebih kemas.' },
    ],
    related: [
      { title: 'Document checklist page', titleMs: 'Halaman senarai semak dokumen', href: '/documents' },
      { title: 'Self-employed income proof guide', titleMs: 'Panduan bukti pendapatan bekerja sendiri', href: '/loan-guides/self-employed-income-proof' },
      { title: 'Review methodology', titleMs: 'Metodologi semakan', href: '/review-methodology' },
    ],
  },
  {
    slug: 'bad-credit-loan-options',
    title: 'Bad Credit Loan Options Malaysia',
    titleMs: 'Pilihan Pinjaman Kredit Lemah Malaysia',
    description: 'A borrower-focused guide to what “bad credit” actually means in Malaysia and which route may still be workable depending on the cause and timing.',
    descriptionMs: 'Panduan berfokus peminjam tentang maksud sebenar “kredit lemah” di Malaysia dan laluan mana yang mungkin masih sesuai bergantung pada punca dan masa.',
    stats: [
      { label: 'Best first action', labelMs: 'Tindakan pertama terbaik', value: 'Diagnose file' },
      { label: 'Worst move', labelMs: 'Langkah paling buruk', value: 'Mass apply' },
      { label: 'Main variables', labelMs: 'Pemboleh ubah utama', value: 'Age + severity' },
      { label: 'Safer window', labelMs: 'Tetingkap lebih selamat', value: 'After cleanup' },
    ],
    stepsTitle: 'How to choose a safer route',
    stepsTitleMs: 'Cara memilih laluan yang lebih selamat',
    steps: [
      { title: 'Define what “bad credit” means in your case', titleMs: 'Tentukan apa maksud “kredit lemah” dalam kes anda', description: 'Old minor late markers, active arrears, and legal records are not the same problem.', descriptionMs: 'Rekod lewat kecil yang lama, tunggakan aktif, dan rekod legal bukan masalah yang sama.' },
      { title: 'Avoid treating urgency as strategy', titleMs: 'Jangan anggap kecemasan sebagai strategi', description: 'Urgency often pushes borrowers into weak applications that create even more declines.', descriptionMs: 'Kecemasan sering menolak peminjam ke arah permohonan lemah yang menghasilkan lebih banyak penolakan.' },
      { title: 'Check whether the issue is file, DSR, or both', titleMs: 'Semak sama ada isu pada fail, DSR, atau kedua-duanya', description: 'A borrower with a weak file and a high DSR needs a different plan from someone with one issue only.', descriptionMs: 'Peminjam dengan fail lemah dan DSR tinggi memerlukan pelan berbeza berbanding seseorang yang hanya ada satu isu.' },
      { title: 'Re-enter through a narrower route', titleMs: 'Masuk semula melalui laluan yang lebih sempit', description: 'Smaller amount, better timing, and stronger supporting proof often matter more than trying more lenders.', descriptionMs: 'Jumlah lebih kecil, masa lebih baik, dan bukti sokongan lebih kuat selalunya lebih penting daripada mencuba lebih banyak lender.' },
    ],
    checklistTitle: 'Useful checks',
    checklistTitleMs: 'Semakan berguna',
    checklist: ['CCRIS and CTOS read', 'Current debt list', 'Latest income proof', 'Recent application history'],
    checklistMs: ['Bacaan CCRIS dan CTOS', 'Senarai hutang semasa', 'Bukti pendapatan terkini', 'Sejarah permohonan terkini'],
    warningsTitle: 'High-risk habits',
    warningsTitleMs: 'Tabiat berisiko tinggi',
    warnings: ['Applying to many lenders in one week', 'Ignoring active arrears', 'Requesting a large amount because of urgency', 'Assuming old issues no longer matter without checking'],
    warningsMs: ['Memohon kepada banyak lender dalam satu minggu', 'Mengabaikan tunggakan aktif', 'Meminta jumlah besar kerana kecemasan', 'Menganggap isu lama sudah tidak penting tanpa menyemak'],
    faqs: [
      { question: 'Can bad credit still be approved?', questionMs: 'Kredit lemah masih boleh diluluskan?', answer: 'Sometimes yes, but the route depends on whether the issue is old, active, legal, repeated, or mainly affordability-related.', answerMs: 'Kadang-kadang boleh, tetapi laluan bergantung pada sama ada isu itu lama, aktif, legal, berulang, atau terutamanya berkaitan kemampuan.' },
      { question: 'Should I try emergency loan ads first?', questionMs: 'Patutkah saya cuba iklan pinjaman kecemasan dahulu?', answer: 'Usually not before understanding the file. Urgency without diagnosis often leads to poor decisions.', answerMs: 'Biasanya tidak sebelum memahami fail. Kecemasan tanpa diagnosis sering membawa kepada keputusan yang lemah.' },
      { question: 'What helps most before reapplying?', questionMs: 'Apa yang paling membantu sebelum mohon semula?', answer: 'Clearer file reading, lower commitments where possible, and a narrower amount request.', answerMs: 'Bacaan fail yang lebih jelas, komitmen lebih rendah jika boleh, dan permintaan jumlah yang lebih sempit.' },
    ],
    related: [
      { title: 'CCRIS and CTOS guide', titleMs: 'Panduan CCRIS dan CTOS', href: '/loan-guides/ccris-ctos' },
      { title: 'Loan rejection recovery guide', titleMs: 'Panduan pulih selepas ditolak', href: '/loan-guides/loan-rejection-recovery' },
      { title: 'Emergency loan page', titleMs: 'Halaman pinjaman kecemasan', href: '/loans/emergency' },
    ],
  },
  {
    slug: 'commission-income-borrowers',
    title: 'Commission Income Borrowers Guide',
    titleMs: 'Panduan Peminjam Pendapatan Komisen',
    description: 'A practical guide for agents and commission-based earners on how to prepare a stronger, more explainable income file.',
    descriptionMs: 'Panduan praktikal untuk ejen dan penerima pendapatan komisen tentang cara menyediakan fail pendapatan yang lebih kuat dan mudah diterangkan.',
    stats: [
      { label: 'Best evidence', labelMs: 'Bukti terbaik', value: 'Consistent credits' },
      { label: 'Useful window', labelMs: 'Tempoh berguna', value: '6-12 months' },
      { label: 'Big risk', labelMs: 'Risiko besar', value: 'Highly uneven months' },
      { label: 'Goal', labelMs: 'Matlamat', value: 'Explainability' },
    ],
    stepsTitle: 'What makes commission income bankable',
    stepsTitleMs: 'Apa yang membuat pendapatan komisen boleh diterima bank',
    steps: [
      { title: 'Show recurring inflow', titleMs: 'Tunjukkan aliran masuk berulang', description: 'Lenders usually care more about recurring credits than one-off strong months.', descriptionMs: 'Lender biasanya lebih mengambil berat tentang kredit berulang daripada bulan kuat sekali-sekala.' },
      { title: 'Support with statements or payout records', titleMs: 'Sokong dengan penyata atau rekod payout', description: 'Commission slips, remittance advice, or platform statements help make the pattern credible.', descriptionMs: 'Slip komisen, nasihat remittance, atau penyata platform membantu menjadikan corak itu lebih dipercayai.' },
      { title: 'Separate business and personal cash noise', titleMs: 'Asingkan gangguan tunai perniagaan dan peribadi', description: 'Mixed transfers with no explanation weaken the file.', descriptionMs: 'Pindahan bercampur tanpa penjelasan melemahkan fail.' },
      { title: 'Use a realistic monthly average', titleMs: 'Gunakan purata bulanan yang realistik', description: 'A sensible averaged figure often works better than presenting only the highest earning month.', descriptionMs: 'Angka purata yang munasabah sering berfungsi lebih baik daripada hanya menunjukkan bulan pendapatan tertinggi.' },
    ],
    checklistTitle: 'Helpful supporting proof',
    checklistTitleMs: 'Bukti sokongan yang membantu',
    checklist: ['Commission statements', 'Bank credits over 6-12 months', 'Agency or contract proof', 'Tax support where available'],
    checklistMs: ['Penyata komisen', 'Kredit bank sepanjang 6-12 bulan', 'Bukti agensi atau kontrak', 'Sokongan cukai jika ada'],
    warningsTitle: 'What weakens the file',
    warningsTitleMs: 'Apa yang melemahkan fail',
    warnings: ['Only showing one strong month', 'No banked trail', 'Cash-heavy income with no explanation', 'Large amount request despite unstable average'],
    warningsMs: ['Hanya menunjukkan satu bulan kuat', 'Tiada jejak bank', 'Pendapatan tunai tinggi tanpa penjelasan', 'Permintaan jumlah besar walaupun purata tidak stabil'],
    faqs: [
      { question: 'Can commission income be accepted?', questionMs: 'Pendapatan komisen boleh diterima?', answer: 'Yes, if the inflow pattern is consistent enough and supported by clear records.', answerMs: 'Ya, jika corak aliran masuk cukup konsisten dan disokong oleh rekod yang jelas.' },
      { question: 'Should I use my highest month to apply?', questionMs: 'Patutkah saya guna bulan tertinggi untuk memohon?', answer: 'Usually no. A more realistic multi-month average is often safer.', answerMs: 'Biasanya tidak. Purata berbilang bulan yang lebih realistik selalunya lebih selamat.' },
      { question: 'Do tax records help?', questionMs: 'Rekod cukai membantu?', answer: 'Yes. They often strengthen the credibility of variable earnings.', answerMs: 'Ya. Ia sering menguatkan kredibiliti pendapatan berubah.' },
    ],
    related: [
      { title: 'Self-employed income proof guide', titleMs: 'Panduan bukti pendapatan bekerja sendiri', href: '/loan-guides/self-employed-income-proof' },
      { title: 'Eligibility test', titleMs: 'Ujian kelayakan', href: '/eligibility-test' },
      { title: 'Review methodology', titleMs: 'Metodologi semakan', href: '/review-methodology' },
    ],
  },
  {
    slug: 'first-time-borrower-checklist',
    title: 'First-Time Borrower Checklist Malaysia',
    titleMs: 'Senarai Semak Peminjam Kali Pertama Malaysia',
    description: 'A first-time borrower guide covering what to check before submitting any loan application for the first time in Malaysia.',
    descriptionMs: 'Panduan peminjam kali pertama tentang apa yang perlu disemak sebelum menghantar sebarang permohonan pinjaman pertama di Malaysia.',
    stats: [
      { label: 'Best first check', labelMs: 'Semakan pertama terbaik', value: 'Credit + DSR' },
      { label: 'Main risk', labelMs: 'Risiko utama', value: 'Wrong first move' },
      { label: 'Priority', labelMs: 'Keutamaan', value: 'Document readiness' },
      { label: 'Safer pace', labelMs: 'Kelajuan lebih selamat', value: 'One route at a time' },
    ],
    stepsTitle: 'A cleaner way to start',
    stepsTitleMs: 'Cara lebih bersih untuk bermula',
    steps: [
      { title: 'Check your record before you ask for money', titleMs: 'Semak rekod anda sebelum minta wang', description: 'Even first-time borrowers may have PTPTN, telco, card, or legal issues they are unaware of.', descriptionMs: 'Walaupun peminjam kali pertama mungkin ada isu PTPTN, telco, kad, atau legal yang mereka tidak sedari.' },
      { title: 'Know your repayment capacity early', titleMs: 'Kenal kemampuan bayaran awal', description: 'The right amount is not the maximum amount. It is the amount your file can realistically support.', descriptionMs: 'Jumlah yang betul bukan jumlah maksimum. Ia ialah jumlah yang fail anda boleh sokong secara realistik.' },
      { title: 'Prepare documents before inquiries spread', titleMs: 'Sediakan dokumen sebelum inquiry tersebar', description: 'Poorly timed first applications create unnecessary early declines.', descriptionMs: 'Permohonan pertama yang waktunya lemah mewujudkan penolakan awal yang tidak perlu.' },
      { title: 'Use one coherent route first', titleMs: 'Gunakan satu laluan yang koheren dahulu', description: 'A targeted application strategy is stronger than testing many routes randomly.', descriptionMs: 'Strategi permohonan yang terarah lebih kuat daripada mencuba banyak laluan secara rawak.' },
    ],
    checklistTitle: 'Starter checklist',
    checklistTitleMs: 'Senarai semak permulaan',
    checklist: ['CCRIS and CTOS review', 'Income proof', 'Bank statements', 'Existing commitments list'],
    checklistMs: ['Semakan CCRIS dan CTOS', 'Bukti pendapatan', 'Penyata bank', 'Senarai komitmen sedia ada'],
    warningsTitle: 'Beginner traps',
    warningsTitleMs: 'Perangkap pemula',
    warnings: ['Applying based on ads alone', 'Skipping file review', 'Ignoring debt-service capacity', 'Submitting incomplete documents'],
    warningsMs: ['Memohon berdasarkan iklan sahaja', 'Melangkau semakan fail', 'Mengabaikan kapasiti debt-service', 'Menghantar dokumen tidak lengkap'],
    faqs: [
      { question: 'Should first-time borrowers start with a bank branch walk-in?', questionMs: 'Peminjam kali pertama patut bermula dengan walk-in bank?', answer: 'Only if the file is ready. Many first applications fail because the borrower has not checked the basics first.', answerMs: 'Hanya jika fail sudah siap. Banyak permohonan pertama gagal kerana peminjam tidak menyemak asas terlebih dahulu.' },
      { question: 'Do I need CCRIS and CTOS if I never had a loan?', questionMs: 'Perlu CCRIS dan CTOS jika saya tak pernah ada pinjaman?', answer: 'It is still useful to confirm there are no hidden issues before your first submission.', answerMs: 'Ia tetap berguna untuk memastikan tiada isu tersembunyi sebelum penghantaran pertama.' },
      { question: 'How many lenders should I try first?', questionMs: 'Berapa banyak lender patut saya cuba dahulu?', answer: 'Usually one targeted route is better than many weak first attempts.', answerMs: 'Biasanya satu laluan terarah lebih baik daripada banyak percubaan pertama yang lemah.' },
    ],
    related: [
      { title: 'Eligibility test', titleMs: 'Ujian kelayakan', href: '/eligibility-test' },
      { title: 'Documents checklist', titleMs: 'Senarai semak dokumen', href: '/loan-guides/topics/personal-loan-documents-checklist' },
      { title: 'Review methodology', titleMs: 'Metodologi semakan', href: '/review-methodology' },
    ],
  },
  {
    slug: 'ccris-cleanup-plan',
    title: 'CCRIS Cleanup Plan Malaysia',
    titleMs: 'Pelan Pembersihan CCRIS Malaysia',
    description: 'A structured cleanup plan for borrowers who need to improve recent repayment behaviour before applying again.',
    descriptionMs: 'Pelan pembersihan berstruktur untuk peminjam yang perlu memperbaiki tingkah laku bayaran terkini sebelum memohon semula.',
    stats: [
      { label: 'Core window', labelMs: 'Tempoh teras', value: '12 months' },
      { label: 'Useful reset', labelMs: 'Reset berguna', value: '3 clean cycles' },
      { label: 'Main goal', labelMs: 'Matlamat utama', value: 'No fresh lates' },
      { label: 'Wrong habit', labelMs: 'Tabiat salah', value: 'Apply while repairing' },
    ],
    stepsTitle: 'What a real cleanup plan looks like',
    stepsTitleMs: 'Bagaimana rupa pelan pembersihan sebenar',
    steps: [
      { title: 'Stop creating fresh late markers', titleMs: 'Hentikan rekod lewat baru', description: 'The cleanup clock does not really start while new missed payments continue.', descriptionMs: 'Jam pembersihan tidak benar-benar bermula selagi bayaran tertunggak baru masih berlaku.' },
      { title: 'Reduce pressure where possible', titleMs: 'Kurangkan tekanan jika boleh', description: 'Cutting card usage or resolving smaller arrears first often helps more than chasing a new loan immediately.', descriptionMs: 'Mengurangkan penggunaan kad atau menyelesaikan tunggakan kecil dahulu sering lebih membantu daripada mengejar pinjaman baru dengan segera.' },
      { title: 'Track month-by-month progress', titleMs: 'Jejak kemajuan bulan demi bulan', description: 'A cleaner recent pattern matters when lenders compare the file now versus the previous decline.', descriptionMs: 'Corak terkini yang lebih bersih penting apabila lender membandingkan fail sekarang berbanding penolakan terdahulu.' },
      { title: 'Re-enter only when the story improved', titleMs: 'Masuk semula hanya apabila cerita fail bertambah baik', description: 'A better application is not just later. It is later plus clearer evidence that behaviour changed.', descriptionMs: 'Permohonan yang lebih baik bukan sekadar lebih lewat. Ia ialah lebih lewat bersama bukti yang lebih jelas bahawa tingkah laku sudah berubah.' },
    ],
    checklistTitle: 'Useful proof during cleanup',
    checklistTitleMs: 'Bukti berguna semasa pembersihan',
    checklist: ['Updated CCRIS report', 'Current payment records', 'Lower card balances', 'Settlement proof where relevant'],
    checklistMs: ['Laporan CCRIS terkini', 'Rekod bayaran semasa', 'Baki kad lebih rendah', 'Bukti settlement jika berkaitan'],
    warningsTitle: 'What slows recovery',
    warningsTitleMs: 'Apa yang melambatkan pemulihan',
    warnings: ['Fresh arrears', 'New applications during repair', 'Keeping utilization very high', 'No evidence of changed behaviour'],
    warningsMs: ['Tunggakan baru', 'Permohonan baru semasa pemulihan', 'Mengekalkan utilization sangat tinggi', 'Tiada bukti perubahan tingkah laku'],
    faqs: [
      { question: 'How fast can CCRIS improve?', questionMs: 'Berapa cepat CCRIS boleh bertambah baik?', answer: 'It depends on the issue, but many borrowers need several clean cycles before the file looks meaningfully stronger.', answerMs: 'Ia bergantung pada isu, tetapi ramai peminjam memerlukan beberapa kitaran bersih sebelum fail kelihatan lebih kuat dengan ketara.' },
      { question: 'Should I wait for a full year?', questionMs: 'Perlukah saya tunggu setahun penuh?', answer: 'Not always. Some cases improve enough earlier, but only after real behaviour changed.', answerMs: 'Tidak semestinya. Sesetengah kes bertambah baik lebih awal, tetapi hanya selepas tingkah laku benar-benar berubah.' },
      { question: 'Does lower card utilization help?', questionMs: 'Utilization kad yang lebih rendah membantu?', answer: 'Yes, especially when it improves affordability and lender comfort at the same time.', answerMs: 'Ya, terutamanya apabila ia memperbaiki kemampuan ansuran dan keyakinan lender pada masa yang sama.' },
    ],
    related: [
      { title: 'Credit score guide', titleMs: 'Panduan skor kredit', href: '/loan-guides/credit-score' },
      { title: 'CCRIS and CTOS guide', titleMs: 'Panduan CCRIS dan CTOS', href: '/loan-guides/ccris-ctos' },
      { title: 'Loan rejection recovery guide', titleMs: 'Panduan pulih selepas ditolak', href: '/loan-guides/loan-rejection-recovery' },
    ],
  },
  {
    slug: 'ctos-legal-records',
    title: 'CTOS Legal Records Guide Malaysia',
    titleMs: 'Panduan Rekod Legal CTOS Malaysia',
    description: 'A practical guide to understanding how legal or collection-style CTOS signals can affect lender confidence and what borrowers should do first.',
    descriptionMs: 'Panduan praktikal untuk memahami bagaimana isyarat CTOS bercorak legal atau collection boleh mempengaruhi keyakinan lender dan apa yang patut peminjam lakukan terlebih dahulu.',
    stats: [
      { label: 'Main risk', labelMs: 'Risiko utama', value: 'Active legal flags' },
      { label: 'Best action', labelMs: 'Tindakan terbaik', value: 'Verify record' },
      { label: 'Priority proof', labelMs: 'Bukti keutamaan', value: 'Settlement / release' },
      { label: 'Wrong move', labelMs: 'Langkah salah', value: 'Ignore and apply' },
    ],
    stepsTitle: 'How to respond to CTOS legal signals',
    stepsTitleMs: 'Cara bertindak balas terhadap isyarat legal CTOS',
    steps: [
      { title: 'Confirm what the record actually says', titleMs: 'Sahkan apa yang sebenarnya dinyatakan rekod', description: 'Borrowers often react to a vague label without understanding whether the issue is active, old, or already settled.', descriptionMs: 'Peminjam sering bertindak balas terhadap label kabur tanpa memahami sama ada isu itu aktif, lama, atau sudah selesai.' },
      { title: 'Collect supporting proof early', titleMs: 'Kumpulkan bukti sokongan lebih awal', description: 'Settlement letters, release notices, and documented explanations can matter more than verbal claims.', descriptionMs: 'Surat settlement, notis pelepasan, dan penjelasan berdokumen boleh menjadi lebih penting daripada dakwaan lisan.' },
      { title: 'Do not over-focus on one flag only', titleMs: 'Jangan terlalu fokus pada satu tanda sahaja', description: 'Lenders still look at affordability, income stability, and overall repayment pattern too.', descriptionMs: 'Lender tetap melihat kemampuan ansuran, kestabilan pendapatan, dan corak bayaran keseluruhan juga.' },
      { title: 'Re-enter only with a cleaner narrative', titleMs: 'Masuk semula hanya dengan naratif yang lebih bersih', description: 'The file should tell a consistent story: what happened, what changed, and what proof now exists.', descriptionMs: 'Fail perlu menceritakan kisah yang konsisten: apa yang berlaku, apa yang berubah, dan bukti apa yang kini wujud.' },
    ],
    checklistTitle: 'Useful supporting records',
    checklistTitleMs: 'Rekod sokongan yang berguna',
    checklist: ['CTOS details', 'Settlement or release letters', 'Updated bank statements', 'Current income proof'],
    checklistMs: ['Butiran CTOS', 'Surat settlement atau release', 'Penyata bank terkini', 'Bukti pendapatan semasa'],
    warningsTitle: 'What hurts credibility',
    warningsTitleMs: 'Apa yang mencederakan kredibiliti',
    warnings: ['No explanation for the record', 'Applying while the issue is still active', 'No supporting documentation', 'Requesting a large amount without cleanup'],
    warningsMs: ['Tiada penjelasan untuk rekod itu', 'Memohon ketika isu masih aktif', 'Tiada dokumentasi sokongan', 'Meminta jumlah besar tanpa pembersihan'],
    faqs: [
      { question: 'Does every CTOS legal record mean automatic rejection?', questionMs: 'Adakah setiap rekod legal CTOS bermaksud penolakan automatik?', answer: 'Not automatically, but active unresolved issues usually create substantial resistance.', answerMs: 'Tidak secara automatik, tetapi isu aktif yang belum selesai biasanya mewujudkan tentangan yang ketara.' },
      { question: 'Does settlement proof help?', questionMs: 'Bukti settlement membantu?', answer: 'Yes. It often changes how the record is interpreted, especially when current behaviour improved too.', answerMs: 'Ya. Ia sering mengubah cara rekod itu ditafsir, terutamanya apabila tingkah laku semasa juga sudah bertambah baik.' },
      { question: 'Should I apply before verifying the record?', questionMs: 'Patut mohon sebelum mengesahkan rekod?', answer: 'Usually no. Verification should happen first.', answerMs: 'Biasanya tidak. Pengesahan patut berlaku dahulu.' },
    ],
    related: [
      { title: 'CCRIS and CTOS guide', titleMs: 'Panduan CCRIS dan CTOS', href: '/loan-guides/ccris-ctos' },
      { title: 'Loan rejection recovery guide', titleMs: 'Panduan pulih selepas ditolak', href: '/loan-guides/loan-rejection-recovery' },
      { title: 'Verify us', titleMs: 'Sahkan kami', href: '/verify-us' },
    ],
  },
  {
    slug: 'debt-settlement-vs-consolidation',
    title: 'Debt Settlement vs Debt Consolidation Malaysia',
    titleMs: 'Penyelesaian Hutang vs Penyatuan Hutang Malaysia',
    description: 'A practical comparison for borrowers deciding whether they need settlement, restructuring, or a consolidation route.',
    descriptionMs: 'Perbandingan praktikal untuk peminjam yang sedang memutuskan sama ada mereka memerlukan settlement, penyusunan semula, atau laluan penyatuan hutang.',
    stats: [
      { label: 'Settlement focus', labelMs: 'Fokus settlement', value: 'Resolve problem debt' },
      { label: 'Consolidation focus', labelMs: 'Fokus penyatuan', value: 'Lower monthly strain' },
      { label: 'Main question', labelMs: 'Soalan utama', value: 'Temporary or structural?' },
      { label: 'Best first step', labelMs: 'Langkah pertama terbaik', value: 'Map all debts' },
    ],
    stepsTitle: 'How to choose the right route',
    stepsTitleMs: 'Cara memilih laluan yang betul',
    steps: [
      { title: 'List every facility clearly', titleMs: 'Senaraikan setiap kemudahan dengan jelas', description: 'You cannot choose well when you only know one or two problem debts but not the full picture.', descriptionMs: 'Anda tidak boleh memilih dengan baik apabila anda hanya tahu satu atau dua hutang bermasalah tetapi bukan gambaran penuh.' },
      { title: 'Decide whether the pressure is monthly or structural', titleMs: 'Tentukan sama ada tekanannya bulanan atau struktur', description: 'Consolidation helps monthly strain; settlement is more relevant when specific debts are already deeply problematic.', descriptionMs: 'Penyatuan membantu tekanan bulanan; settlement lebih relevan apabila hutang tertentu sudah benar-benar bermasalah.' },
      { title: 'Estimate the repayment path honestly', titleMs: 'Anggarkan laluan bayaran dengan jujur', description: 'A lower instalment that lasts too long may still be the wrong answer if behaviour does not change.', descriptionMs: 'Ansuran lebih rendah yang terlalu panjang masih boleh menjadi jawapan salah jika tingkah laku tidak berubah.' },
      { title: 'Use the route that stabilises the file first', titleMs: 'Gunakan laluan yang menstabilkan fail dahulu', description: 'For some borrowers, the priority is to stop deterioration before chasing an ideal rate.', descriptionMs: 'Bagi sesetengah peminjam, keutamaannya ialah menghentikan kemerosotan sebelum mengejar kadar ideal.' },
    ],
    checklistTitle: 'Useful inputs',
    checklistTitleMs: 'Input yang berguna',
    checklist: ['Debt list with balances', 'Minimum payments', 'Income proof', 'Any legal or arrears status'],
    checklistMs: ['Senarai hutang dengan baki', 'Bayaran minimum', 'Bukti pendapatan', 'Sebarang status legal atau tunggakan'],
    warningsTitle: 'What creates the wrong decision',
    warningsTitleMs: 'Apa yang mencipta keputusan salah',
    warnings: ['Looking only at monthly instalment', 'Ignoring high-risk debts', 'Extending tenure blindly', 'Trying to solve structural debt with another weak application'],
    warningsMs: ['Hanya melihat ansuran bulanan', 'Mengabaikan hutang berisiko tinggi', 'Memanjangkan tempoh secara membuta tuli', 'Mencuba menyelesaikan hutang struktur dengan satu lagi permohonan lemah'],
    faqs: [
      { question: 'Is consolidation always better than settlement?', questionMs: 'Penyatuan sentiasa lebih baik daripada settlement?', answer: 'No. They solve different problems.', answerMs: 'Tidak. Kedua-duanya menyelesaikan masalah yang berbeza.' },
      { question: 'Can I consolidate while still in arrears?', questionMs: 'Boleh saya menyatukan hutang ketika masih ada tunggakan?', answer: 'Sometimes, but route fit depends on severity, current income, and file condition.', answerMs: 'Kadang-kadang, tetapi kesesuaian laluan bergantung pada tahap serius, pendapatan semasa, dan keadaan fail.' },
      { question: 'What should I review first?', questionMs: 'Apa yang patut saya semak dahulu?', answer: 'The full debt map, minimum payments, and whether the main pressure is monthly or legal/structural.', answerMs: 'Peta hutang penuh, bayaran minimum, dan sama ada tekanan utama bersifat bulanan atau legal/struktur.' },
    ],
    related: [
      { title: 'Debt consolidation guide', titleMs: 'Panduan penyatuan hutang', href: '/loan-guides/debt-consolidation' },
      { title: 'Compare loans', titleMs: 'Bandingkan pinjaman', href: '/compare' },
      { title: 'Loan rejection recovery guide', titleMs: 'Panduan pulih selepas ditolak', href: '/loan-guides/loan-rejection-recovery' },
    ],
  },
  {
    slug: 'emergency-loan-safety-checklist',
    title: 'Emergency Loan Safety Checklist Malaysia',
    titleMs: 'Senarai Semak Keselamatan Pinjaman Kecemasan Malaysia',
    description: 'A practical safety checklist for borrowers under time pressure who still need to verify the route before sending money or documents.',
    descriptionMs: 'Senarai semak keselamatan praktikal untuk peminjam yang berada di bawah tekanan masa tetapi masih perlu mengesahkan laluan sebelum menghantar wang atau dokumen.',
    stats: [
      { label: 'Best rule', labelMs: 'Peraturan terbaik', value: 'Verify first' },
      { label: 'Biggest risk', labelMs: 'Risiko terbesar', value: 'Urgency + poor checks' },
      { label: 'Safer path', labelMs: 'Laluan lebih selamat', value: 'Small + documented' },
      { label: 'Wrong move', labelMs: 'Langkah salah', value: 'Pay before clarity' },
    ],
    stepsTitle: 'How to stay safer under pressure',
    stepsTitleMs: 'Cara kekal lebih selamat walaupun tertekan',
    steps: [
      { title: 'Define the exact amount needed', titleMs: 'Tentukan jumlah tepat yang diperlukan', description: 'A tighter amount often creates better decisions than chasing a large emergency buffer.', descriptionMs: 'Jumlah yang lebih ketat sering menghasilkan keputusan lebih baik berbanding mengejar penampan kecemasan yang besar.' },
      { title: 'Verify identity and official channels', titleMs: 'Sahkan identiti dan saluran rasmi', description: 'Urgency is exactly when poor actors try to take advantage of borrowers.', descriptionMs: 'Kecemasan ialah waktu apabila pihak tidak bertanggungjawab cuba mengambil kesempatan ke atas peminjam.' },
      { title: 'Read repayment, not just ad language', titleMs: 'Baca bayaran balik, bukan bahasa iklan sahaja', description: 'What matters is the real repayment structure, not only “fast approval” language.', descriptionMs: 'Yang penting ialah struktur bayaran balik sebenar, bukan bahasa “kelulusan pantas” semata-mata.' },
      { title: 'Keep the request as narrow as possible', titleMs: 'Kekalkan permintaan sesempit mungkin', description: 'Smaller, clearer requests are often safer than broad urgent borrowing.', descriptionMs: 'Permintaan yang lebih kecil dan jelas selalunya lebih selamat berbanding pinjaman kecemasan yang luas.' },
    ],
    checklistTitle: 'Emergency checks',
    checklistTitleMs: 'Semakan kecemasan',
    checklist: ['Official contact verification', 'Real repayment amount', 'Amount truly needed', 'Income and repayment capacity'],
    checklistMs: ['Pengesahan hubungan rasmi', 'Jumlah bayaran balik sebenar', 'Jumlah yang benar-benar diperlukan', 'Pendapatan dan kemampuan bayaran balik'],
    warningsTitle: 'High-risk warning signs',
    warningsTitleMs: 'Tanda amaran berisiko tinggi',
    warnings: ['Pressure to pay first', 'No written terms', 'No clear identity trail', 'Approval promise without checks'],
    warningsMs: ['Tekanan untuk bayar dahulu', 'Tiada terma bertulis', 'Tiada jejak identiti yang jelas', 'Janji kelulusan tanpa semakan'],
    faqs: [
      { question: 'Should urgency change my standards?', questionMs: 'Patutkah kecemasan mengubah standard saya?', answer: 'No. It should make verification more important, not less.', answerMs: 'Tidak. Ia patut menjadikan pengesahan lebih penting, bukan kurang penting.' },
      { question: 'What matters most in an emergency route?', questionMs: 'Apa yang paling penting dalam laluan kecemasan?', answer: 'Identity, repayment clarity, and whether the amount is actually supportable.', answerMs: 'Identiti, kejelasan bayaran balik, dan sama ada jumlah itu benar-benar boleh ditampung.' },
      { question: 'Can a smaller amount be safer?', questionMs: 'Jumlah lebih kecil boleh jadi lebih selamat?', answer: 'Often yes, especially when affordability is tight.', answerMs: 'Selalunya ya, terutamanya apabila kemampuan ansuran ketat.' },
    ],
    related: [
      { title: 'Emergency loan page', titleMs: 'Halaman pinjaman kecemasan', href: '/loans/emergency' },
      { title: 'Verify us', titleMs: 'Sahkan kami', href: '/verify-us' },
      { title: 'Licensed lender checklist', titleMs: 'Senarai semak lender berlesen', href: '/loan-guides/topics/licensed-lender-checklist' },
    ],
  },
  {
    slug: 'licensed-lender-checklist',
    title: 'Licensed Lender Checklist Malaysia',
    titleMs: 'Senarai Semak Lender Berlesen Malaysia',
    description: 'A verification checklist for borrowers who want to compare lender routes more carefully before proceeding.',
    descriptionMs: 'Senarai semak pengesahan untuk peminjam yang mahu membandingkan laluan lender dengan lebih teliti sebelum meneruskan.',
    stats: [
      { label: 'Core check', labelMs: 'Semakan teras', value: 'Identity + process' },
      { label: 'Big red flag', labelMs: 'Tanda amaran besar', value: 'Personal account payment' },
      { label: 'Better habit', labelMs: 'Tabiat lebih baik', value: 'Read written terms' },
      { label: 'Wrong focus', labelMs: 'Fokus salah', value: 'Ad claims only' },
    ],
    stepsTitle: 'How to verify more carefully',
    stepsTitleMs: 'Cara mengesahkan dengan lebih teliti',
    steps: [
      { title: 'Check company and office identity', titleMs: 'Semak identiti syarikat dan pejabat', description: 'Borrowers should know exactly who they are dealing with before sharing documents or money.', descriptionMs: 'Peminjam patut tahu dengan tepat siapa yang mereka berurusan sebelum berkongsi dokumen atau wang.' },
      { title: 'Review the process in writing', titleMs: 'Semak proses secara bertulis', description: 'A cleaner route is explained through official written steps, not just rushed chats.', descriptionMs: 'Laluan yang lebih bersih diterangkan melalui langkah bertulis rasmi, bukan sekadar chat tergesa-gesa.' },
      { title: 'Understand the repayment structure', titleMs: 'Fahami struktur bayaran balik', description: 'Monthly affordability matters, but total repayment and risk behaviour matter too.', descriptionMs: 'Kemampuan bulanan penting, tetapi jumlah bayaran balik dan tingkah laku berisiko juga penting.' },
      { title: 'Stop at the first major red flag', titleMs: 'Berhenti pada tanda amaran besar yang pertama', description: 'Borrowers under stress often ignore the first warning sign and regret it later.', descriptionMs: 'Peminjam yang tertekan sering mengabaikan tanda amaran pertama dan menyesal kemudian.' },
    ],
    checklistTitle: 'Verification checklist',
    checklistTitleMs: 'Senarai semak pengesahan',
    checklist: ['Official website and contact path', 'Office or company identity', 'Written steps and terms', 'Repayment and fee explanation'],
    checklistMs: ['Laman web rasmi dan laluan hubungan', 'Identiti pejabat atau syarikat', 'Langkah dan terma bertulis', 'Penjelasan bayaran balik dan yuran'],
    warningsTitle: 'Do not ignore these',
    warningsTitleMs: 'Jangan abaikan perkara ini',
    warnings: ['Payment to personal accounts', 'No written explanation', 'Pressure to decide immediately', 'Claims of guaranteed approval'],
    warningsMs: ['Bayaran ke akaun peribadi', 'Tiada penjelasan bertulis', 'Tekanan untuk buat keputusan segera', 'Dakwaan kelulusan terjamin'],
    faqs: [
      { question: 'Is every licensed route automatically safe?', questionMs: 'Adakah setiap laluan berlesen secara automatik selamat?', answer: 'No. Borrowers still need to verify identity, process, and repayment clarity.', answerMs: 'Tidak. Peminjam tetap perlu mengesahkan identiti, proses, dan kejelasan bayaran balik.' },
      { question: 'Should I proceed if terms are unclear?', questionMs: 'Patutkah saya teruskan jika terma tidak jelas?', answer: 'No. Lack of clarity is itself a warning sign.', answerMs: 'Tidak. Kekurangan kejelasan itu sendiri ialah tanda amaran.' },
      { question: 'What is the safest first action?', questionMs: 'Apakah tindakan pertama yang paling selamat?', answer: 'Verify the company, official channel, and written process before sending anything.', answerMs: 'Sahkan syarikat, saluran rasmi, dan proses bertulis sebelum menghantar apa-apa.' },
    ],
    related: [
      { title: 'Verify us', titleMs: 'Sahkan kami', href: '/verify-us' },
      { title: 'Emergency loan safety checklist', titleMs: 'Senarai semak keselamatan pinjaman kecemasan', href: '/loan-guides/topics/emergency-loan-safety-checklist' },
      { title: 'Review methodology', titleMs: 'Metodologi semakan', href: '/review-methodology' },
    ],
  },
  {
    slug: 'small-loan-amount-guide',
    title: 'Small Loan Amount Guide Malaysia',
    titleMs: 'Panduan Jumlah Pinjaman Kecil Malaysia',
    description: 'A practical guide for smaller loan requests and how lenders may view amount, urgency, and affordability together.',
    descriptionMs: 'Panduan praktikal untuk permohonan pinjaman kecil dan bagaimana lender mungkin melihat jumlah, kecemasan, dan kemampuan secara bersama.',
    stats: [
      { label: 'Best fit', labelMs: 'Kesesuaian terbaik', value: 'Specific purpose' },
      { label: 'Key benefit', labelMs: 'Manfaat utama', value: 'Lower strain' },
      { label: 'Main risk', labelMs: 'Risiko utama', value: 'Urgent repeat borrowing' },
      { label: 'Goal', labelMs: 'Matlamat', value: 'Smaller and cleaner' },
    ],
    stepsTitle: 'How to approach a smaller request well',
    stepsTitleMs: 'Cara mendekati permintaan kecil dengan baik',
    steps: [
      { title: 'Tie the amount to a real purpose', titleMs: 'Ikat jumlah kepada tujuan sebenar', description: 'A clearer purpose often makes the request easier to structure and assess.', descriptionMs: 'Tujuan yang lebih jelas sering menjadikan permintaan lebih mudah distruktur dan dinilai.' },
      { title: 'Do not assume small means automatic approval', titleMs: 'Jangan anggap kecil bermaksud lulus automatik', description: 'File quality still matters, even when the requested amount is modest.', descriptionMs: 'Kualiti fail tetap penting walaupun jumlah diminta kecil.' },
      { title: 'Use the smaller request to improve fit', titleMs: 'Gunakan permintaan kecil untuk meningkatkan kesesuaian', description: 'A smaller amount can help affordability, but only when the rest of the file is still coherent.', descriptionMs: 'Jumlah lebih kecil boleh membantu kemampuan, tetapi hanya apabila baki fail masih koheren.' },
      { title: 'Avoid turning small into frequent', titleMs: 'Elak menjadikan kecil sebagai kerap', description: 'Repeated small borrowing can still signal stress when it becomes a pattern.', descriptionMs: 'Pinjaman kecil berulang masih boleh menandakan tekanan apabila ia menjadi corak.' },
    ],
    checklistTitle: 'Useful prep',
    checklistTitleMs: 'Persediaan berguna',
    checklist: ['Exact amount needed', 'Purpose of funds', 'Income proof', 'Current commitments'],
    checklistMs: ['Jumlah tepat diperlukan', 'Tujuan dana', 'Bukti pendapatan', 'Komitmen semasa'],
    warningsTitle: 'What weakens small requests',
    warningsTitleMs: 'Apa yang melemahkan permintaan kecil',
    warnings: ['Using urgency language only', 'No clear purpose', 'Weak file despite small amount', 'Repeated short-gap borrowing'],
    warningsMs: ['Menggunakan bahasa kecemasan sahaja', 'Tiada tujuan yang jelas', 'Fail lemah walaupun jumlah kecil', 'Pinjaman berulang dengan jarak masa pendek'],
    faqs: [
      { question: 'Is a smaller amount easier to approve?', questionMs: 'Jumlah lebih kecil lebih mudah diluluskan?', answer: 'Sometimes, especially on affordability grounds, but it does not override major file issues.', answerMs: 'Kadang-kadang, terutamanya dari sudut kemampuan, tetapi ia tidak mengatasi isu fail utama.' },
      { question: 'Should I still review CCRIS and CTOS first?', questionMs: 'Masih perlu semak CCRIS dan CTOS dahulu?', answer: 'Yes. Smaller amount does not remove the need for file awareness.', answerMs: 'Ya. Jumlah lebih kecil tidak menghapuskan keperluan untuk memahami fail.' },
      { question: 'Can repeated small loans hurt me?', questionMs: 'Pinjaman kecil berulang boleh menjejaskan saya?', answer: 'Yes, if it creates a visible stress pattern or rising commitments.', answerMs: 'Ya, jika ia mewujudkan corak tekanan yang ketara atau komitmen meningkat.' },
    ],
    related: [
      { title: 'Personal loan minimum salary guide', titleMs: 'Panduan gaji minimum pinjaman peribadi', href: '/loan-guides/topics/personal-loan-minimum-salary' },
      { title: 'Emergency loan safety checklist', titleMs: 'Senarai semak keselamatan pinjaman kecemasan', href: '/loan-guides/topics/emergency-loan-safety-checklist' },
      { title: 'Personal loan page', titleMs: 'Halaman pinjaman peribadi', href: '/loans/personal' },
    ],
  },
  {
    slug: 'high-dsr-recovery',
    title: 'High DSR Recovery Guide Malaysia',
    titleMs: 'Panduan Pemulihan DSR Tinggi Malaysia',
    description: 'A practical guide for borrowers whose debt-service ratio is already too high for the route they want.',
    descriptionMs: 'Panduan praktikal untuk peminjam yang nisbah debt-service mereka sudah terlalu tinggi untuk laluan yang mereka mahukan.',
    stats: [
      { label: 'Common target', labelMs: 'Sasaran biasa', value: '< 60-70%' },
      { label: 'Main issue', labelMs: 'Isu utama', value: 'Commitment pressure' },
      { label: 'Best move', labelMs: 'Langkah terbaik', value: 'Recalculate honestly' },
      { label: 'Wrong move', labelMs: 'Langkah salah', value: 'Guess and apply' },
    ],
    stepsTitle: 'How to recover from a high DSR position',
    stepsTitleMs: 'Cara pulih daripada kedudukan DSR tinggi',
    steps: [
      { title: 'Recalculate every commitment properly', titleMs: 'Kira semula setiap komitmen dengan betul', description: 'Borrowers often underestimate card minimums and hidden recurring obligations.', descriptionMs: 'Peminjam sering meremehkan minimum kad dan obligasi berulang yang tersembunyi.' },
      { title: 'Lower the monthly burden first', titleMs: 'Kurangkan beban bulanan dahulu', description: 'A route that reduces monthly pressure may help more than pushing for a new large facility.', descriptionMs: 'Laluan yang mengurangkan tekanan bulanan mungkin lebih membantu daripada memaksa kemudahan besar baharu.' },
      { title: 'Avoid fresh debt while repairing', titleMs: 'Elakkan hutang baharu ketika membaiki', description: 'Trying to stack new borrowing on top of high DSR usually worsens the file.', descriptionMs: 'Mencuba menambah pinjaman baharu di atas DSR tinggi biasanya memburukkan fail.' },
      { title: 'Re-enter with a smaller or more suitable route', titleMs: 'Masuk semula dengan laluan lebih kecil atau lebih sesuai', description: 'The next best step may be consolidation, cleanup, or waiting rather than a direct application.', descriptionMs: 'Langkah terbaik seterusnya mungkin penyatuan, pembersihan, atau menunggu, bukannya permohonan terus.' },
    ],
    checklistTitle: 'What to map out',
    checklistTitleMs: 'Apa yang perlu dipetakan',
    checklist: ['All instalments', 'Card minimums', 'Net income', 'Any debt reduction options'],
    checklistMs: ['Semua ansuran', 'Minimum kad', 'Pendapatan bersih', 'Sebarang pilihan pengurangan hutang'],
    warningsTitle: 'What worsens DSR problems',
    warningsTitleMs: 'Apa yang memburukkan masalah DSR',
    warnings: ['Guessing current ratios', 'Applying without recalculation', 'Keeping expensive short-term debt active', 'Ignoring monthly pressure'],
    warningsMs: ['Meneka nisbah semasa', 'Memohon tanpa pengiraan semula', 'Mengekalkan hutang jangka pendek mahal yang aktif', 'Mengabaikan tekanan bulanan'],
    faqs: [
      { question: 'Can high DSR still be fixed?', questionMs: 'DSR tinggi masih boleh diperbaiki?', answer: 'Yes, but usually through a staged recovery plan rather than a rushed new application.', answerMs: 'Ya, tetapi biasanya melalui pelan pemulihan berperingkat, bukan permohonan baharu yang tergesa-gesa.' },
      { question: 'Does higher income automatically solve DSR?', questionMs: 'Pendapatan lebih tinggi menyelesaikan DSR secara automatik?', answer: 'Not always. Existing commitments and file quality still matter.', answerMs: 'Tidak semestinya. Komitmen sedia ada dan kualiti fail tetap penting.' },
      { question: 'What helps most first?', questionMs: 'Apa yang paling membantu dahulu?', answer: 'An honest recalculation and a clearer map of monthly commitments.', answerMs: 'Pengiraan semula yang jujur dan peta komitmen bulanan yang lebih jelas.' },
    ],
    related: [
      { title: 'Debt consolidation guide', titleMs: 'Panduan penyatuan hutang', href: '/loan-guides/debt-consolidation' },
      { title: 'Compare loans', titleMs: 'Bandingkan pinjaman', href: '/compare' },
      { title: 'Eligibility test', titleMs: 'Ujian kelayakan', href: '/eligibility-test' },
    ],
  },
  {
    slug: 'personal-loan-amount-guide',
    title: 'Personal Loan Amount Guide Malaysia',
    titleMs: 'Panduan Jumlah Pinjaman Peribadi Malaysia',
    description: 'A practical guide to matching requested loan amount with income strength, existing commitments, and overall file quality.',
    descriptionMs: 'Panduan praktikal untuk memadankan jumlah pinjaman diminta dengan kekuatan pendapatan, komitmen sedia ada, dan kualiti fail keseluruhan.',
    stats: [
      { label: 'Main fit factor', labelMs: 'Faktor kesesuaian utama', value: 'Income + DSR' },
      { label: 'Overlooked issue', labelMs: 'Isu terlepas pandang', value: 'File quality' },
      { label: 'Safer strategy', labelMs: 'Strategi lebih selamat', value: 'Realistic amount' },
      { label: 'Wrong approach', labelMs: 'Pendekatan salah', value: 'Ask maximum first' },
    ],
    stepsTitle: 'How to size the request better',
    stepsTitleMs: 'Cara menentukan saiz permintaan dengan lebih baik',
    steps: [
      { title: 'Start from monthly capacity', titleMs: 'Mulakan daripada kapasiti bulanan', description: 'Loan amount should follow repayment fit, not only aspiration.', descriptionMs: 'Jumlah pinjaman patut mengikut kesesuaian bayaran balik, bukan sekadar aspirasi.' },
      { title: 'Adjust for file strength', titleMs: 'Laraskan ikut kekuatan fail', description: 'A clean strong file can support a different amount from a weak or newly repaired one.', descriptionMs: 'Fail yang bersih dan kuat boleh menyokong jumlah berbeza berbanding fail lemah atau yang baru dipulihkan.' },
      { title: 'Match amount with urgency honestly', titleMs: 'Padankan jumlah dengan kecemasan secara jujur', description: 'Borrow only what solves the real need instead of building a risky buffer.', descriptionMs: 'Pinjam hanya apa yang menyelesaikan keperluan sebenar dan bukannya membina penampan berisiko.' },
      { title: 'Use amount as a lever, not just a target', titleMs: 'Gunakan jumlah sebagai tuas, bukan sekadar sasaran', description: 'Changing the amount can improve fit when affordability is the main blocker.', descriptionMs: 'Mengubah jumlah boleh memperbaiki kesesuaian apabila kemampuan ansuran ialah halangan utama.' },
    ],
    checklistTitle: 'What to review first',
    checklistTitleMs: 'Apa yang perlu disemak dahulu',
    checklist: ['Net income', 'Current commitments', 'Credit file condition', 'Real use of funds'],
    checklistMs: ['Pendapatan bersih', 'Komitmen semasa', 'Keadaan fail kredit', 'Penggunaan sebenar dana'],
    warningsTitle: 'Amount-sizing mistakes',
    warningsTitleMs: 'Kesilapan menentukan jumlah',
    warnings: ['Asking based on headline ads', 'Ignoring monthly strain', 'Not adjusting after a rejection', 'Using one exceptional income month'],
    warningsMs: ['Meminta berdasarkan iklan utama', 'Mengabaikan tekanan bulanan', 'Tidak melaras selepas penolakan', 'Menggunakan satu bulan pendapatan luar biasa'],
    faqs: [
      { question: 'Should I always ask for the maximum?', questionMs: 'Patutkah saya sentiasa minta jumlah maksimum?', answer: 'Usually no. A more realistic request often improves fit and reduces decline risk.', answerMs: 'Biasanya tidak. Permintaan yang lebih realistik sering meningkatkan kesesuaian dan mengurangkan risiko ditolak.' },
      { question: 'Can lowering the amount help?', questionMs: 'Merendahkan jumlah boleh membantu?', answer: 'Yes, especially when affordability is borderline.', answerMs: 'Ya, terutamanya apabila kemampuan berada di sempadan.' },
      { question: 'Does file quality affect amount?', questionMs: 'Kualiti fail mempengaruhi jumlah?', answer: 'Absolutely. Amount fit is tied to both income and credit profile.', answerMs: 'Sudah tentu. Kesesuaian jumlah berkait dengan pendapatan dan profil kredit.' },
    ],
    related: [
      { title: 'Personal loan minimum salary guide', titleMs: 'Panduan gaji minimum pinjaman peribadi', href: '/loan-guides/topics/personal-loan-minimum-salary' },
      { title: 'High DSR recovery guide', titleMs: 'Panduan pemulihan DSR tinggi', href: '/loan-guides/topics/high-dsr-recovery' },
      { title: 'Personal loan page', titleMs: 'Halaman pinjaman peribadi', href: '/loans/personal' },
    ],
  },
  {
    slug: 'credit-file-audit-before-apply',
    title: 'Credit File Audit Before Applying',
    titleMs: 'Audit Fail Kredit Sebelum Memohon',
    description: 'A borrower checklist for reviewing credit-file quality before any serious loan submission.',
    descriptionMs: 'Senarai semak peminjam untuk menyemak kualiti fail kredit sebelum sebarang penghantaran pinjaman yang serius.',
    stats: [
      { label: 'Main goal', labelMs: 'Matlamat utama', value: 'Know file condition' },
      { label: 'Best sequence', labelMs: 'Urutan terbaik', value: 'Read -> fix -> apply' },
      { label: 'Wrong habit', labelMs: 'Tabiat salah', value: 'Apply blind' },
      { label: 'Best tool', labelMs: 'Alat terbaik', value: 'Combined review' },
    ],
    stepsTitle: 'What a real pre-application audit includes',
    stepsTitleMs: 'Apa yang termasuk dalam audit pra-permohonan sebenar',
    steps: [
      { title: 'Repayment history review', titleMs: 'Semakan sejarah bayaran', description: 'Look at current and recent patterns, not only whether there is any issue at all.', descriptionMs: 'Lihat corak semasa dan terkini, bukan sekadar sama ada ada isu atau tidak.' },
      { title: 'Affordability map', titleMs: 'Peta kemampuan', description: 'Check whether obligations already compress borrowing headroom before you choose a route.', descriptionMs: 'Semak sama ada obligasi sedia ada sudah mengecilkan ruang pinjaman sebelum anda memilih laluan.' },
      { title: 'Document readiness check', titleMs: 'Semakan kesiapsiagaan dokumen', description: 'A decent file still fails when the documents are weak or inconsistent.', descriptionMs: 'Fail yang baik pun boleh gagal apabila dokumen lemah atau tidak konsisten.' },
      { title: 'Route selection', titleMs: 'Pemilihan laluan', description: 'Decide whether your next step is bank, consolidation, cleanup, or waiting.', descriptionMs: 'Tentukan sama ada langkah seterusnya ialah bank, penyatuan, pembersihan, atau menunggu.' },
    ],
    checklistTitle: 'Audit inputs',
    checklistTitleMs: 'Input audit',
    checklist: ['CCRIS / CTOS', 'Income proof', 'Debt list', 'Recent inquiry pattern'],
    checklistMs: ['CCRIS / CTOS', 'Bukti pendapatan', 'Senarai hutang', 'Corak inquiry terkini'],
    warningsTitle: 'What blind applications miss',
    warningsTitleMs: 'Apa yang aplikasi membuta tuli terlepas pandang',
    warnings: ['Hidden DSR pressure', 'Weak supporting proof', 'Recent unresolved issues', 'Wrong product route'],
    warningsMs: ['Tekanan DSR tersembunyi', 'Bukti sokongan lemah', 'Isu terkini yang belum selesai', 'Laluan produk yang salah'],
    faqs: [
      { question: 'Why audit before applying?', questionMs: 'Mengapa audit sebelum memohon?', answer: 'Because many declines come from problems the borrower could have seen earlier with a proper file review.', answerMs: 'Kerana banyak penolakan datang daripada masalah yang peminjam boleh nampak lebih awal dengan semakan fail yang betul.' },
      { question: 'Is this only for weak files?', questionMs: 'Adakah ini hanya untuk fail lemah?', answer: 'No. Even stronger borrowers benefit from cleaner route selection and document readiness.', answerMs: 'Tidak. Peminjam yang lebih kuat pun mendapat manfaat daripada pemilihan laluan yang lebih bersih dan kesiapsiagaan dokumen.' },
      { question: 'What usually changes after an audit?', questionMs: 'Apa yang biasanya berubah selepas audit?', answer: 'The amount, route, timing, or document pack often becomes more realistic.', answerMs: 'Jumlah, laluan, masa, atau pakej dokumen selalunya menjadi lebih realistik.' },
    ],
    related: [
      { title: 'Review methodology', titleMs: 'Metodologi semakan', href: '/review-methodology' },
      { title: 'Editorial policy', titleMs: 'Dasar editorial', href: '/editorial-policy' },
      { title: 'Eligibility test', titleMs: 'Ujian kelayakan', href: '/eligibility-test' },
    ],
  },
  {
    slug: 'borrower-red-flags-checklist',
    title: 'Borrower Red Flags Checklist Malaysia',
    titleMs: 'Senarai Semak Tanda Amaran Peminjam Malaysia',
    description: 'A checklist of borrower-side red flags that often reduce lender confidence before the application is even read in depth.',
    descriptionMs: 'Senarai semak tanda amaran dari sisi peminjam yang sering mengurangkan keyakinan lender sebelum permohonan dibaca secara mendalam pun.',
    stats: [
      { label: 'Common issue', labelMs: 'Isu biasa', value: 'Inconsistency' },
      { label: 'Big risk', labelMs: 'Risiko besar', value: 'Too many inquiries' },
      { label: 'Main fix', labelMs: 'Pembetulan utama', value: 'Cleaner file story' },
      { label: 'Goal', labelMs: 'Matlamat', value: 'Reduce friction' },
    ],
    stepsTitle: 'What often makes lenders uncomfortable',
    stepsTitleMs: 'Apa yang sering membuat lender tidak selesa',
    steps: [
      { title: 'Inconsistent income story', titleMs: 'Cerita pendapatan yang tidak konsisten', description: 'When documents and bank flows do not match, the whole file becomes harder to trust.', descriptionMs: 'Apabila dokumen dan aliran bank tidak sepadan, seluruh fail menjadi lebih sukar dipercayai.' },
      { title: 'Stress signals in recent behaviour', titleMs: 'Isyarat tekanan dalam tingkah laku terkini', description: 'Repeated applications, arrears, or sharp card usage spikes often matter more than borrowers expect.', descriptionMs: 'Permohonan berulang, tunggakan, atau lonjakan penggunaan kad yang ketara sering lebih penting daripada yang dijangka peminjam.' },
      { title: 'Weak or rushed documentation', titleMs: 'Dokumentasi lemah atau tergesa-gesa', description: 'Poorly prepared files create avoidable friction even when the profile is workable.', descriptionMs: 'Fail yang disediakan dengan lemah mewujudkan geseran yang boleh dielakkan walaupun profil masih boleh diusahakan.' },
      { title: 'Mismatch between need and route', titleMs: 'Ketidakpadanan antara keperluan dan laluan', description: 'Borrowers often choose routes based on urgency or ads instead of actual suitability.', descriptionMs: 'Peminjam sering memilih laluan berdasarkan kecemasan atau iklan dan bukannya kesesuaian sebenar.' },
    ],
    checklistTitle: 'Red flags worth checking',
    checklistTitleMs: 'Tanda amaran yang patut disemak',
    checklist: ['Too many recent applications', 'Unexplained income movements', 'Fresh late markers', 'Very high card utilization'],
    checklistMs: ['Terlalu banyak permohonan terkini', 'Pergerakan pendapatan tanpa penjelasan', 'Rekod lewat baru', 'Utilization kad sangat tinggi'],
    warningsTitle: 'What happens if ignored',
    warningsTitleMs: 'Apa yang berlaku jika diabaikan',
    warnings: ['More declines', 'More inquiries on file', 'Lower lender confidence', 'Harder recovery later'],
    warningsMs: ['Lebih banyak penolakan', 'Lebih banyak inquiry pada fail', 'Keyakinan lender lebih rendah', 'Pemulihan lebih sukar kemudian'],
    faqs: [
      { question: 'Are these red flags always fatal?', questionMs: 'Adakah tanda amaran ini sentiasa fatal?', answer: 'Not always, but they often reduce lender comfort enough to change the route or timing.', answerMs: 'Tidak semestinya, tetapi ia sering mengurangkan keselesaan lender sehingga mengubah laluan atau masa.' },
      { question: 'Can a strong salary offset them?', questionMs: 'Gaji kuat boleh mengimbangi semua ini?', answer: 'Sometimes partly, but not consistently.', answerMs: 'Kadang-kadang sebahagiannya, tetapi tidak secara konsisten.' },
      { question: 'What is the safest response?', questionMs: 'Apakah tindak balas paling selamat?', answer: 'Diagnose the red flags before another submission.', answerMs: 'Diagnosis tanda amaran itu dahulu sebelum penghantaran seterusnya.' },
    ],
    related: [
      { title: 'Credit file audit before applying', titleMs: 'Audit fail kredit sebelum memohon', href: '/loan-guides/topics/credit-file-audit-before-apply' },
      { title: 'Loan rejection recovery guide', titleMs: 'Panduan pulih selepas ditolak', href: '/loan-guides/loan-rejection-recovery' },
      { title: 'CCRIS cleanup plan', titleMs: 'Pelan pembersihan CCRIS', href: '/loan-guides/topics/ccris-cleanup-plan' },
    ],
  },
];

export function getGuideTopic(slug: string) {
  return guideTopics.find((topic) => topic.slug === slug);
}
